with open('src/translations.ts', 'r', encoding='utf-8') as f:
    text = f.read()

dicts = {
    'bn': '''    coins: "কয়েন",
    streak: "দিন",
    continueText: "চালিয়ে যান",
    dailyGoalTitle: "দৈনিক শিক্ষামূলক লক্ষ্য",
    dailyGoalSubtitle: "আজকের ১৫ মিনিটের পাঠ সম্পন্ন করুন",
    quickLearning: "দ্রুত শিখুন",
    viewMore: "আরও দেখুন",
    qaidaTitle: "নূরানী কায়দা",
    gamesTitle: "মজার সাথে শিখুন",
    aiTajweedTitle: "ভয়েস সহ",
    homeNav: "হোম",
    liveClassNav: "লাইভ ক্লাস",
    gamesNav: "গেমস",
    qaidaQuranNav: "কায়দা ও কুরআন",
    parentNav: "অভিভাবক",
    madrasaPanelTitle: "তালিমুল কুরআন অনলাইন (মাদ্রাসা প্যানেল)",
    madrasaPanelBadge: "সম্পূর্ণ সিস্টেম",
    madrasaPanelDesc: "শিক্ষক ও ছাত্র ভর্তি, ক্লাস, ফি, হাজিরা, সবক শোনা ও পরীক্ষা পদ্ধতি",
    openPanel: "প্যানেল খুলুন",''',
    'en': '''    coins: "Coins",
    streak: "Days",
    continueText: "Continue",
    dailyGoalTitle: "Daily Learning Goal",
    dailyGoalSubtitle: "Complete today's 15 min lesson",
    quickLearning: "Quick Learning",
    viewMore: "View More",
    qaidaTitle: "Noorani Qaida",
    gamesTitle: "Learn with Fun",
    aiTajweedTitle: "With Voice",
    homeNav: "Home",
    liveClassNav: "Live Class",
    gamesNav: "Games",
    qaidaQuranNav: "Qaida & Quran",
    parentNav: "Parent",
    madrasaPanelTitle: "Talimul Quran Online (Madrasa Panel)",
    madrasaPanelBadge: "Complete System",
    madrasaPanelDesc: "Teachers & Students admission, classes, fees, attendance, lesson listening & exam system",
    openPanel: "Open Panel",''',
    'ar': '''    coins: "عملات",
    streak: "أيام",
    continueText: "متابعة",
    dailyGoalTitle: "الهدف التعليمي اليومي",
    dailyGoalSubtitle: "أكمل درس اليوم لمدة 15 دقيقة",
    quickLearning: "تعلم سريع",
    viewMore: "عرض المزيد",
    qaidaTitle: "القاعدة النورانية",
    gamesTitle: "تعلم بمتعة",
    aiTajweedTitle: "بالصوت",
    homeNav: "الرئيسية",
    liveClassNav: "درس مباشر",
    gamesNav: "ألعاب",
    qaidaQuranNav: "القاعدة والقرآن",
    parentNav: "أولياء الأمور",
    madrasaPanelTitle: "تعليم القرآن عبر الإنترنت (لوحة المدرسة)",
    madrasaPanelBadge: "نظام متكامل",
    madrasaPanelDesc: "تسجيل المعلمين والطلاب، الفصول، الرسوم، الحضور، الاستماع للدروس ونظام الامتحانات",
    openPanel: "فتح اللوحة",''',
    'ur': '''    coins: "سکے",
    streak: "دن",
    continueText: "جاری رکھیں",
    dailyGoalTitle: "روزانہ تعلیمی ہدف",
    dailyGoalSubtitle: "آج کا 15 منٹ سبق مکمل کریں",
    quickLearning: "فوری سیکھیں",
    viewMore: "مزید دیکھیں",
    qaidaTitle: "نورانی قاعدہ",
    gamesTitle: "مزے کے ساتھ سیکھیں",
    aiTajweedTitle: "آواز کے ساتھ",
    homeNav: "ہوم",
    liveClassNav: "لائیو کلاس",
    gamesNav: "گیمز",
    qaidaQuranNav: "قاعدہ و قرآن",
    parentNav: "والدین",
    madrasaPanelTitle: "تعلیم القرآن آن لائن (مدرسہ پینل)",
    madrasaPanelBadge: "مکمل نظام",
    madrasaPanelDesc: "اساتذہ و طلباء شمولیت، کلاسیں، فیس، حاضری، سبق سماعت اور امتحانی نظام",
    openPanel: "اوپن کریں پینل",''',
    'hi': '''    coins: "सिक्के",
    streak: "दिन",
    continueText: "जारी रखें",
    dailyGoalTitle: "दैनिक शिक्षण लक्ष्य",
    dailyGoalSubtitle: "आज का 15 मिनट का पाठ पूरा करें",
    quickLearning: "त्वरित सीख",
    viewMore: "और देखें",
    qaidaTitle: "नूरानी कायदा",
    gamesTitle: "मज़े के साथ सीखें",
    aiTajweedTitle: "आवाज़ के साथ",
    homeNav: "होम",
    liveClassNav: "लाइव क्लास",
    gamesNav: "गेम्स",
    qaidaQuranNav: "कायदा और क़ुरआन",
    parentNav: "माता-पिता",
    madrasaPanelTitle: "तालीमुल क़ुरआन ऑनलाइन (मदरसा पैनल)",
    madrasaPanelBadge: "पूर्ण सिस्टम",
    madrasaPanelDesc: "शिक्षक और छात्र प्रवेश, कक्षाएं, शुल्क, उपस्थिति, पाठ सुनना और परीक्षा प्रणाली",
    openPanel: "पैनल खोलें",''',
    'id': '''    coins: "Koin",
    streak: "Hari",
    continueText: "Lanjutkan",
    dailyGoalTitle: "Target Belajar Harian",
    dailyGoalSubtitle: "Selesaikan pelajaran 15 menit hari ini",
    quickLearning: "Belajar Cepat",
    viewMore: "Lihat Lainnya",
    qaidaTitle: "Qaidah Noorani",
    gamesTitle: "Belajar dengan Seru",
    aiTajweedTitle: "Dengan Suara",
    homeNav: "Beranda",
    liveClassNav: "Kelas Live",
    gamesNav: "Game",
    qaidaQuranNav: "Qaidah & Quran",
    parentNav: "Orang Tua",
    madrasaPanelTitle: "Talimul Quran Online (Panel Madrasah)",
    madrasaPanelBadge: "Sistem Lengkap",
    madrasaPanelDesc: "Pendaftaran guru & siswa, kelas, biaya, absensi, mendengarkan pelajaran & sistem ujian",
    openPanel: "Buka Panel",''',
    'tr': '''    coins: "Jeton",
    streak: "Gün",
    continueText: "Devam Et",
    dailyGoalTitle: "Günlük Öğrenme Hedefi",
    dailyGoalSubtitle: "Bugünkü 15 dakikalık dersi tamamla",
    quickLearning: "Hızlı Öğrenme",
    viewMore: "Daha Fazla",
    qaidaTitle: "Nurani Kaide",
    gamesTitle: "Eğlenerek Öğren",
    aiTajweedTitle: "Sesli",
    homeNav: "Ana Sayfa",
    liveClassNav: "Canlı Ders",
    gamesNav: "Oyunlar",
    qaidaQuranNav: "Kaide & Kur'an",
    parentNav: "Ebeveyn",
    madrasaPanelTitle: "Talimul Kur'an Çevrimiçi (Medrese Paneli)",
    madrasaPanelBadge: "Tam Sistem",
    madrasaPanelDesc: "Öğretmen ve öğrenci kaydı, dersler, ücretler, devamlılık, ders dinleme ve sınav sistemi",
    openPanel: "Paneli Aç",''',
    'fr': '''    coins: "Pièces",
    streak: "Jours",
    continueText: "Continuer",
    dailyGoalTitle: "Objectif d'Apprentissage Quotidien",
    dailyGoalSubtitle: "Terminez la leçon de 15 minutes d'aujourd'hui",
    quickLearning: "Apprentissage Rapide",
    viewMore: "Voir Plus",
    qaidaTitle: "Qaida Noorani",
    gamesTitle: "Apprendre en S'amusant",
    aiTajweedTitle: "Avec Voix",
    homeNav: "Accueil",
    liveClassNav: "Cours en direct",
    gamesNav: "Jeux",
    qaidaQuranNav: "Qaida & Coran",
    parentNav: "Parents",
    madrasaPanelTitle: "Talimul Quran En Ligne (Panneau Madrasa)",
    madrasaPanelBadge: "Système Complet",
    madrasaPanelDesc: "Admission des enseignants et étudiants, cours, frais, présence, écoute des leçons et système d'examen",
    openPanel: "Ouvrir le Panneau",''',
}

for lang, snippet in dicts.items():
    marker = f"{lang}: {{"
    if marker in text:
        sub_str = text[text.find(marker):text.find(marker)+500]
        if 'coins:' not in sub_str:
            idx = text.find(marker) + len(marker)
            text = text[:idx] + "\n" + snippet + text[idx:]

with open('src/translations.ts', 'w', encoding='utf-8') as f:
    f.write(text)

print('translations.ts updated successfully')
