import { LanguageCode } from '../types';

export interface BlankBoardTexts {
  back: string;
  lessonEyebrow: string;
  title: string;
  description: string;
  progress: string;
  huntModeBtn: string;
  sequentialModeBtn: string;
  targetCardLabel: string;
  letterNumberPrefix: string;
  listen: string;
  totalSearchLabel: string;
  hintBtn: string;
  shuffleBtn: string;
  playAudioBtn: string;
  restartBtn: string;
  xpLabel: string;
  coinsLabel: string;
  streakLabel: string;
  bestStreakLabel: string;
  completedTitle: string;
  completedDesc: string;
  playAgain: string;
  alreadyFoundMsg: (name: string) => string;
  alreadyFoundSub: (name: string, letter: string) => string;
  wrongMsg: (name: string) => string;
  wrongSub: (name: string, letter: string) => string;
  hintMsg: string;
  hintSub: (name: string, letter: string) => string;
  shuffledMsg: string;
  shuffledSub: (name: string) => string;
  sequentialSetMsg: string;
  sequentialSetSub: string;
  huntSetMsg: string;
  huntSetSub: string;
}

export const BLANK_BOARD_LOCALIZATION: Record<LanguageCode, BlankBoardTexts> = {
  ur: {
    back: 'واپسی',
    lessonEyebrow: 'سبق نمبر ۱: حروفِ تہجی و مفردات (۲۹ حروف)',
    title: 'حروفِ تہجی بلینک بورڈ',
    description: 'تمام ۲۹ حروفِ تہجی کو بورڈ پر تلاش کریں اور شناخت کی پکی مشق کریں۔',
    progress: 'پروگریس',
    huntModeBtn: '🎲 بے ترتیب تلاش موڈ (بہترین مشق)',
    sequentialModeBtn: '🔤 ترتیب وار بورڈ (الف تا یا)',
    targetCardLabel: 'ابھی نیچے دیے گئے بکھرے ہوئے بورڈ سے یہ حرف تلاش کریں:',
    letterNumberPrefix: 'حرف نمبر #',
    listen: 'سنیں',
    totalSearchLabel: 'کُل حروف کی تلاش',
    hintBtn: '💡 اشارہ (Hint)',
    shuffleBtn: '🔀 شفل کریں',
    playAudioBtn: '🔊 آواز سنیں',
    restartBtn: '↻ دوبارہ شروع',
    xpLabel: 'کل تجربہ',
    coinsLabel: 'سکے',
    streakLabel: 'تسلسل',
    bestStreakLabel: 'بہترین تسلسل',
    completedTitle: 'ماشاءاللہ! کھیل مکمل ہوگیا',
    completedDesc: 'آپ نے تمام 29 حروفِ تہجی کامیابی سے تلاش کر کے مکمل کر لیے۔',
    playAgain: 'دوبارہ کھیلیں (بے ترتیب مشق)',
    alreadyFoundMsg: (name) => `یہ حرف "${name}" آپ تلاش کر چکے ہیں!`,
    alreadyFoundSub: (name, letter) => `اب مطلوبہ حرف "${name}" (${letter}) تلاش کریں`,
    wrongMsg: (name) => `یہ "${name}" ہے، دوبارہ کوشش کریں!`,
    wrongSub: (name, letter) => `ابھی مطلوبہ حرف "${name}" (${letter}) تلاش کریں`,
    hintMsg: '💡 اشارہ!',
    hintSub: (name, letter) => `مطلوبہ حرف "${name}" (${letter}) بورڈ پر چمک رہا ہے`,
    shuffledMsg: 'بورڈ شفل ہوگیا 🔀',
    shuffledSub: (name) => `اب مطلوبہ حرف "${name}" تلاش کریں`,
    sequentialSetMsg: 'ترتیب وار بورڈ سیٹ ہو گیا 🔤',
    sequentialSetSub: 'حروف الف تا یا سیدھی ترتیب میں ہیں',
    huntSetMsg: 'بے ترتیب / تلاش موڈ فعال 🎲',
    huntSetSub: 'حروف بکھر گئے ہیں، ہر حرف کو غور سے تلاش کریں!',
  },
  en: {
    back: 'Back',
    lessonEyebrow: 'Lesson 1: Individual Arabic Alphabet (29 Letters)',
    title: 'Arabic Letters Blank Board',
    description: 'Find and recognize all 29 Arabic letters on the interactive board.',
    progress: 'Progress',
    huntModeBtn: '🎲 Shuffled Hunt Mode (Best Practice)',
    sequentialModeBtn: '🔤 Sequential Board (Alif to Yaa)',
    targetCardLabel: 'Find this target letter on the board below:',
    letterNumberPrefix: 'Letter #',
    listen: 'Listen',
    totalSearchLabel: 'Total Letters Found',
    hintBtn: '💡 Hint',
    shuffleBtn: '🔀 Shuffle',
    playAudioBtn: '🔊 Play Audio',
    restartBtn: '↻ Restart',
    xpLabel: 'Total XP',
    coinsLabel: 'Coins',
    streakLabel: 'Streak',
    bestStreakLabel: 'Best Streak',
    completedTitle: 'MashaAllah! Board Completed',
    completedDesc: 'You have successfully identified and completed all 29 letters!',
    playAgain: 'Play Again (Shuffled Hunt)',
    alreadyFoundMsg: (name) => `Letter "${name}" is already completed!`,
    alreadyFoundSub: (name, letter) => `Now find target letter "${name}" (${letter})`,
    wrongMsg: (name) => `This is "${name}", try again!`,
    wrongSub: (name, letter) => `Now look for target "${name}" (${letter})`,
    hintMsg: '💡 Hint!',
    hintSub: (name, letter) => `Target letter "${name}" (${letter}) is glowing on the board`,
    shuffledMsg: 'Board Shuffled 🔀',
    shuffledSub: (name) => `Now find target letter "${name}"`,
    sequentialSetMsg: 'Sequential Board Activated 🔤',
    sequentialSetSub: 'Letters are arranged in standard Alif to Yaa order',
    huntSetMsg: 'Hunt Mode Activated 🎲',
    huntSetSub: 'Letters are scrambled, look closely and recognize each letter!',
  },
  ar: {
    back: 'رجوع',
    lessonEyebrow: 'الدرس الأول: الحروف المفردة الهجائية (٢٩ حرفاً)',
    title: 'لوحة الحروف الهجائية التفاعلية',
    description: 'ابحث عن جميع الحروف الهجائية الـ ٢٩ وميّزها على اللوحة.',
    progress: 'التقدم',
    huntModeBtn: '🎲 وضع البحث العشوائي (أفضل تمرين)',
    sequentialModeBtn: '🔤 لوحة مرتبة (من الألف إلى الياء)',
    targetCardLabel: 'ابحث عن هذا الحرف المطلوب في اللوحة أدناه:',
    letterNumberPrefix: 'الحرف رقم #',
    listen: 'استمع',
    totalSearchLabel: 'مجموع الحروف المكتشفة',
    hintBtn: '💡 تلميح',
    shuffleBtn: '🔀 خلط اللوحة',
    playAudioBtn: '🔊 استماع للصوت',
    restartBtn: '↻ إعادة البدء',
    xpLabel: 'نقاط الخبرة',
    coinsLabel: 'العملات',
    streakLabel: 'التتابع',
    bestStreakLabel: 'أفضل تتابع',
    completedTitle: 'ما شاء الله! اكتملت اللوحة بنجاح',
    completedDesc: 'لقد أكملت بنجاح تمييز جميع الحروف الهجائية الـ ٢٩.',
    playAgain: 'العب مجدداً (تمرين عشوائي)',
    alreadyFoundMsg: (name) => `حرف "${name}" تم إيجاده مسبقاً!`,
    alreadyFoundSub: (name, letter) => `ابحث الآن عن الحرف المطلوب "${name}" (${letter})`,
    wrongMsg: (name) => `هذا حرف "${name}"، حاول مرة أخرى!`,
    wrongSub: (name, letter) => `ابحث الآن عن الحرف المطلوب "${name}" (${letter})`,
    hintMsg: '💡 تلميح!',
    hintSub: (name, letter) => `الحرف المطلوب "${name}" (${letter}) يضيء على اللوحة`,
    shuffledMsg: 'تم خلط اللوحة 🔀',
    shuffledSub: (name) => `ابحث الآن عن الحرف المطلوب "${name}"`,
    sequentialSetMsg: 'تم تعيين اللوحة المرتبة 🔤',
    sequentialSetSub: 'الحروف مرتبة من الألف إلى الياء بالتسلسل',
    huntSetMsg: 'تم تفعيل وضع البحث العشوائي 🎲',
    huntSetSub: 'الحروف مبعثرة، ابحث بتركيز ودقة!',
  },
  hi: {
    back: 'वापस',
    lessonEyebrow: 'सबक १: हुरूफ-ए-तहज्जी व मुफ़्रदात (२९ अक्षर)',
    title: 'अरबी अक्षर ब्लैंक बोर्ड गेम',
    description: 'बोर्ड पर सभी २९ अरबी अक्षरों को खोजें और उनकी सही पहचान का अभ्यास करें।',
    progress: 'प्रगति',
    huntModeBtn: '🎲 रैंडम खोज मोड (सर्वोत्तम अभ्यास)',
    sequentialModeBtn: '🔤 क्रमानुसार बोर्ड (अलिफ़ से या)',
    targetCardLabel: 'नीचे दिए गए बोर्ड में इस अक्षर को खोजें:',
    letterNumberPrefix: 'अक्षर #',
    listen: 'सुनें',
    totalSearchLabel: 'कुल खोजे गए अक्षर',
    hintBtn: '💡 इशारा (Hint)',
    shuffleBtn: '🔀 शफ़ल करें',
    playAudioBtn: '🔊 आवाज़ सुनें',
    restartBtn: '↻ फिर से शुरू करें',
    xpLabel: 'कुल अनुभव (XP)',
    coinsLabel: 'सिक्के',
    streakLabel: 'लगातार सही',
    bestStreakLabel: 'सर्वश्रेष्ठ स्ट्रीक',
    completedTitle: 'माशाअल्लाह! खेल पूरा हुआ',
    completedDesc: 'आपने सभी २९ अरबी अक्षरों को सफलतापूर्वक पहचान लिया है।',
    playAgain: 'दोबारा खेलें',
    alreadyFoundMsg: (name) => `अक्षर "${name}" आप पहले ही खोज चुके हैं!`,
    alreadyFoundSub: (name, letter) => `अब लक्ष्य अक्षर "${name}" (${letter}) खोजें`,
    wrongMsg: (name) => `यह "${name}" है, पुनः प्रयास करें!`,
    wrongSub: (name, letter) => `अब लक्ष्य अक्षर "${name}" (${letter}) खोजें`,
    hintMsg: '💡 इशारा!',
    hintSub: (name, letter) => `वांछित अक्षर "${name}" (${letter}) बोर्ड पर चमक रहा है`,
    shuffledMsg: 'बोर्ड शफ़ल हो गया 🔀',
    shuffledSub: (name) => `अब अक्षर "${name}" खोजें`,
    sequentialSetMsg: 'क्रमानुसार बोर्ड सक्रिय 🔤',
    sequentialSetSub: 'अक्षर अलिफ़ से या तक सीधे क्रम में हैं',
    huntSetMsg: 'रैंडम खोज मोड सक्रिय 🎲',
    huntSetSub: 'अक्षर बिखरे हुए हैं, ध्यान से खोजें!',
  },
  bn: {
    back: 'ফিরে যান',
    lessonEyebrow: 'পাঠ ১: আরবি হরফ ও মুফরাদাত (২৯টি হরফ)',
    title: 'আরবি হরফ সন্ধান ও ব্ল্যাঙ্ক বোর্ড',
    description: 'বোর্ড থেকে ২৯টি হরফ সঠিকভাবে চিনে অনুশীলন সম্পন্ন করুন।',
    progress: 'অগ্রগতি',
    huntModeBtn: '🎲 র্যান্ডম সন্ধান মোড (সেরা অনুশীলন)',
    sequentialModeBtn: '🔤 ক্রমানুযায়ী বোর্ড (আলিফ থেকে ইয়া)',
    targetCardLabel: 'নিচের বোর্ড থেকে এই হরফটি খুঁজে বের করুন:',
    letterNumberPrefix: 'হরফ নং #',
    listen: 'শুনুন',
    totalSearchLabel: 'মোট প্রাপ্ত হরফ',
    hintBtn: '💡 ইঙ্গিত (Hint)',
    shuffleBtn: '🔀 এলোমেলো করুন',
    playAudioBtn: '🔊 অডিও শুনুন',
    restartBtn: '↻ পুনরায় শুরু',
    xpLabel: 'মোট XP',
    coinsLabel: 'মুদ্রা',
    streakLabel: 'ধারাবাহিকতা',
    bestStreakLabel: 'সেরা ধারাবাহিকতা',
    completedTitle: 'মাশাআল্লাহ! সম্পন্ন হয়েছে',
    completedDesc: 'আপনি সফলভাবে সব ২৯টি আরবি হরফ চিহ্নিত করেছেন।',
    playAgain: 'আবার খেলুন',
    alreadyFoundMsg: (name) => `হরফ "${name}" ইতিমধ্যে পাওয়া গেছে!`,
    alreadyFoundSub: (name, letter) => `এখন লক্ষ্য হরফ "${name}" (${letter}) খুঁজুন`,
    wrongMsg: (name) => `এটি "${name}", আবার চেষ্টা করুন!`,
    wrongSub: (name, letter) => `এখন লক্ষ্য হরফ "${name}" (${letter}) খুঁজুন`,
    hintMsg: '💡 ইঙ্গিত!',
    hintSub: (name, letter) => `লক্ষ্য হরফ "${name}" (${letter}) বোর্ডে জ্বলজ্বল করছে`,
    shuffledMsg: 'বোর্ড এলোমেলো করা হয়েছে 🔀',
    shuffledSub: (name) => `এখন লক্ষ্য হরফ "${name}" খুঁজুন`,
    sequentialSetMsg: 'ক্রমানুযায়ী বোর্ড প্রস্তুত 🔤',
    sequentialSetSub: 'হরফগুলো আলিফ থেকে ইয়া পর্যন্ত সাজানো আছে',
    huntSetMsg: 'অনুসন্ধান মোড সক্রিয় 🎲',
    huntSetSub: 'হরফগুলো ছড়িয়ে আছে, মনোযোগ দিয়ে সন্ধান করুন!',
  },
  id: {
    back: 'Kembali',
    lessonEyebrow: 'Pelajaran 1: Huruf Hijaiyah Tunggal (29 Huruf)',
    title: 'Papan Pencarian Huruf Hijaiyah',
    description: 'Temukan dan kenali ke-29 huruf hijaiyah pada papan interaktif ini.',
    progress: 'Kemajuan',
    huntModeBtn: '🎲 Mode Acak (Latihan Terbaik)',
    sequentialModeBtn: '🔤 Papan Urut (Alif sampai Ya)',
    targetCardLabel: 'Cari huruf target berikut di papan bawah:',
    letterNumberPrefix: 'Huruf ke-#',
    listen: 'Dengarkan',
    totalSearchLabel: 'Total Huruf Ditemukan',
    hintBtn: '💡 Petunjuk',
    shuffleBtn: '🔀 Acak Papan',
    playAudioBtn: '🔊 Dengar Suara',
    restartBtn: '↻ Mulai Ulang',
    xpLabel: 'Total XP',
    coinsLabel: 'Koin',
    streakLabel: 'Runtunan',
    bestStreakLabel: 'Runtunan Terbaik',
    completedTitle: 'MashaAllah! Papan Selesai',
    completedDesc: 'Anda berhasil menemukan dan mengenali seluruh 29 huruf hijaiyah!',
    playAgain: 'Main Lagi (Mode Acak)',
    alreadyFoundMsg: (name) => `Huruf "${name}" sudah ditemukan sebelumnya!`,
    alreadyFoundSub: (name, letter) => `Sekarang cari huruf target "${name}" (${letter})`,
    wrongMsg: (name) => `Ini adalah "${name}", coba lagi!`,
    wrongSub: (name, letter) => `Sekarang cari huruf target "${name}" (${letter})`,
    hintMsg: '💡 Petunjuk!',
    hintSub: (name, letter) => `Huruf target "${name}" (${letter}) bersinar di papan`,
    shuffledMsg: 'Papan Diacak 🔀',
    shuffledSub: (name) => `Sekarang cari huruf "${name}"`,
    sequentialSetMsg: 'Papan Urut Aktif 🔤',
    sequentialSetSub: 'Huruf tersusun rapi dari Alif hingga Ya',
    huntSetMsg: 'Mode Acak Aktif 🎲',
    huntSetSub: 'Huruf tersebar acak, kenali setiap huruf dengan teliti!',
  },
  tr: {
    back: 'Geri',
    lessonEyebrow: 'Ders 1: Müfredat Harfleri (29 Harf)',
    title: 'Arapça Harf Bulma Panosu',
    description: 'Etkileşimli tahtada 29 Arapça harfi bulun ve tanıma pratiği yapın.',
    progress: 'İlerleme',
    huntModeBtn: '🎲 Karışık Arama Modu (En İyi Pratik)',
    sequentialModeBtn: '🔤 Sıralı Pano (Elif\'ten Ye\'ye)',
    targetCardLabel: 'Aşağıdaki panodan bu hedef harfi bulun:',
    letterNumberPrefix: 'Harf No #',
    listen: 'Dinle',
    totalSearchLabel: 'Bulunan Toplam Harf',
    hintBtn: '💡 İpucu',
    shuffleBtn: '🔀 Karıştır',
    playAudioBtn: '🔊 Sesi Dinle',
    restartBtn: '↻ Yeniden Başlat',
    xpLabel: 'Toplam XP',
    coinsLabel: 'Altın',
    streakLabel: 'Seri',
    bestStreakLabel: 'En İyi Seri',
    completedTitle: 'MaşaAllah! Pano Tamamlandı',
    completedDesc: '29 harfin tamamını başarıyla tanıdınız ve tamamladınız!',
    playAgain: 'Tekrar Oyna (Karışık Mod)',
    alreadyFoundMsg: (name) => `"${name}" harfi zaten tamamlandı!`,
    alreadyFoundSub: (name, letter) => `Şimdi hedef "${name}" (${letter}) harfini arayın`,
    wrongMsg: (name) => `Bu "${name}", tekrar deneyin!`,
    wrongSub: (name, letter) => `Şimdi hedef "${name}" (${letter}) harfini bulun`,
    hintMsg: '💡 İpucu!',
    hintSub: (name, letter) => `Hedef "${name}" (${letter}) tahtada parlıyor`,
    shuffledMsg: 'Pano Karıştırıldı 🔀',
    shuffledSub: (name) => `Şimdi hedef harf "${name}"i arayın`,
    sequentialSetMsg: 'Sıralı Pano Aktif 🔤',
    sequentialSetSub: 'Harfler Elif\'ten Ye\'ye doğru dizildi',
    huntSetMsg: 'Arama Modu Aktif 🎲',
    huntSetSub: 'Harfler dağıtıldı, dikkatlice arayıp bulun!',
  },
  fr: {
    back: 'Retour',
    lessonEyebrow: 'Leçon 1 : Lettres Isolées de l\'Alphabet (29 lettres)',
    title: 'Tableau Interactif des Lettres Arabes',
    description: 'Retrouvez et reconnaissez les 29 lettres arabes sur le tableau interactif.',
    progress: 'Progression',
    huntModeBtn: '🎲 Mode Recherche Aléatoire (Meilleure pratique)',
    sequentialModeBtn: '🔤 Tableau Séquentiel (Alif à Yaa)',
    targetCardLabel: 'Trouvez cette lettre cible sur le tableau ci-dessous :',
    letterNumberPrefix: 'Lettre n° #',
    listen: 'Écouter',
    totalSearchLabel: 'Total Lettres Trouvées',
    hintBtn: '💡 Indice',
    shuffleBtn: '🔀 Mélanger',
    playAudioBtn: '🔊 Écouter l\'audio',
    restartBtn: '↻ Recommencer',
    xpLabel: 'Total XP',
    coinsLabel: 'Pièces',
    streakLabel: 'Série',
    bestStreakLabel: 'Meilleure Série',
    completedTitle: 'MashaAllah ! Tableau Terminé',
    completedDesc: 'Vous avez identifié et terminé avec succès les 29 lettres !',
    playAgain: 'Rejouer (Mode Aléatoire)',
    alreadyFoundMsg: (name) => `La lettre "${name}" a déjà été trouvée !`,
    alreadyFoundSub: (name, letter) => `Cherchez maintenant la lettre cible "${name}" (${letter})`,
    wrongMsg: (name) => `C'est "${name}", essayez encore !`,
    wrongSub: (name, letter) => `Cherchez maintenant la lettre cible "${name}" (${letter})`,
    hintMsg: '💡 Indice !',
    hintSub: (name, letter) => `La lettre cible "${name}" (${letter}) brille sur le tableau`,
    shuffledMsg: 'Tableau Mélangé 🔀',
    shuffledSub: (name) => `Cherchez maintenant la lettre "${name}"`,
    sequentialSetMsg: 'Tableau Séquentiel Activé 🔤',
    sequentialSetSub: 'Les lettres sont ordonnées de Alif à Yaa',
    huntSetMsg: 'Mode Recherche Activé 🎲',
    huntSetSub: 'Les lettres sont éparpillées, observez attentivement !',
  },
};

export const getBlankBoardLocalization = (lang: LanguageCode = 'ur'): BlankBoardTexts => {
  return BLANK_BOARD_LOCALIZATION[lang] || BLANK_BOARD_LOCALIZATION.ur;
};
