import { LanguageCode } from '../types';

export interface MakharijItem {
  category: string;
  huruf: string;
  title: string;
  desc: string;
}

export interface MakharijModalTexts {
  backBtn: string;
  chartBadge: string;
  bismillah: string;
  chartTitle: string;
  meaningLabel: string;
  meaningText: string;
  countText: string;
  tableHeadCategory: string;
  tableHeadHuruf: string;
  tableHeadTitle: string;
  tableHeadDesc: string;
  tableHeadAudio: string;
  listenBtn: string;
  closeBtn: string;
  items: MakharijItem[];
}

export const MAKHARIJ_LOCALIZATION: Record<LanguageCode, MakharijModalTexts> = {
  ur: {
    backBtn: 'واپسی',
    chartBadge: 'مخارج چارٹ',
    bismillah: 'اَلحَمْدُ لِلَّهِ رَبِّ العٰلَمِينَ وَالصَّلَوٰةُ وَالسَّلَامُ عَلَى سَيِّدِ الْمُرْسَلِينَ أَمَّا بَعْدُ فَأَعُوذُ بِاللَّهِ مِنَ الشَّيْطٰنِ الرَّجِيمِ ط بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ط',
    chartTitle: 'حروف کے مخارج کا نقشہ (Makharij-ul-Huruf Chart)',
    meaningLabel: 'مخرج کا لغوی معنی:',
    meaningText: '"نکلنے کی جگہ" ہے اور اصطلاح تجوید میں جس جگہ سے حرف ادا ہوتا ہے اسے "مخرج" کہتے ہیں۔',
    countText: 'مخارج کی تعداد کے بارے میں ائمہ کرام کے مختلف اقوال ہیں، حضرت امام خلیل بن احمد اور اکثر ائمہ کے نزدیک مخارج کی تعداد سترہ (۱۷) ہے۔',
    tableHeadCategory: 'مخرج کا نام',
    tableHeadHuruf: 'حروف',
    tableHeadTitle: 'حروف کے القاب',
    tableHeadDesc: 'مخارج (تفصیل)',
    tableHeadAudio: 'آواز',
    listenBtn: 'سنیں',
    closeBtn: 'بند کریں',
    items: [
      { category: 'حلقی مخارج', huruf: 'ء ، ه', title: 'حُرُوفِ حَلْقِيَّة', desc: 'حلق کے نیچے والے حصے (اقصی حلق) سے ادا ہوتے ہیں۔' },
      { category: 'حلقی مخارج', huruf: 'ع ، ح', title: 'حُرُوفِ حَلْقِيَّة', desc: 'حلق کے درمیان والے حصے (وسط حلق) سے ادا ہوتے ہیں۔' },
      { category: 'حلقی مخارج', huruf: 'غ ، خ', title: 'حُرُوفِ حَلْقِيَّة', desc: 'حلق کے اوپر والے حصے (ادنی حلق) سے ادا ہوتے ہیں۔' },
      { category: 'لسانی مخارج', huruf: 'ق', title: 'حُرُوفِ لَهْوِيَّة', desc: 'زبان کی جڑ اور تالو کے نرم حصے سے ادا ہوتا ہے۔' },
      { category: 'لسانی مخارج', huruf: 'ك', title: 'حُرُوفِ لَهْوِيَّة', desc: 'زبان کی جڑ اور تالو کے سخت حصے سے ادا ہوتا ہے۔' },
      { category: 'لسانی مخارج', huruf: 'ج ، ش ، ی', title: 'حُرُوفِ شَجَرِيَّة', desc: 'زبان کے درمیانی حصے اور مقابل تالو سے ادا ہوتے ہیں۔' },
      { category: 'لسانی مخارج', huruf: 'ض', title: 'حرفِ حَافِيَّة', desc: 'زبان کی کروٹ اور اوپر کی داڑھوں کی جڑ سے ادا ہوتا ہے۔' },
      { category: 'لسانی مخارج', huruf: 'ل', title: 'حُرُوفِ طَرَفِيَّة', desc: 'زبان کا کنارہ اور مسوڑھوں سے ادا ہوتا ہے۔' },
      { category: 'لسانی مخارج', huruf: 'ن', title: 'حُرُوفِ طَرَفِيَّة', desc: 'زبان کا کنارہ اور دانتوں کی جڑوں سے ادا ہوتا ہے۔' },
      { category: 'لسانی مخارج', huruf: 'ر', title: 'حُرُوفِ طَرَفِيَّة', desc: 'زبان کی نوک اور مقابل تالو سے ادا ہوتا ہے۔' },
      { category: 'لسانی مخارج', huruf: 'ط ، د ، ت', title: 'حُرُوفِ نِطْعِيَّة', desc: 'زبان کی نوک اور اوپر کے سامنے والے دانتوں کی جڑ سے ادا ہوتے ہیں۔' },
      { category: 'لسانی مخارج', huruf: 'ظ ، ذ ، ث', title: 'حُرُوفِ لَثَوِيَّة', desc: 'زبان کا سرا اور اوپر کے اگلے دانتوں کے اندرونی کنارے سے ادا ہوتے ہیں۔' },
      { category: 'لسانی مخارج', huruf: 'ص ، ز ، س', title: 'حُرُوفِ صَفِيرِيَّة', desc: 'زبان کی نوک اور دونوں دانتوں کے اندرونی کنارے سے ادا ہوتے ہیں۔' },
      { category: 'شفوی مخارج', huruf: 'ف', title: 'حُرُوفِ شَفَوِيَّة', desc: 'اوپر کے دانتوں کے کنارے اور نچلے ہونٹ کے اندرونی ترچھے حصے سے ادا ہوتا ہے۔' },
      { category: 'شفوی مخارج', huruf: 'ب ، م ، و', title: 'حُرُوفِ شَفَوِيَّة', desc: '"ب" اور "م" دونوں ہونٹوں سے اور "و" ہونٹوں کی گولائی سے ادا ہوتا ہے۔' },
      { category: 'جوفی مخرج', huruf: 'حروفِ مدہ (ا ، و ، ی)', title: 'جوفِ دہن', desc: 'منہ اور گلے کے اندرونی خالی حصے سے ادا ہوتے ہیں۔' },
      { category: 'خیشوم', huruf: '(ناک کا بانسہ)', title: 'غُنّہ کا مخرج', desc: 'ناک کے بانسے سے گنگناہٹ کی آواز ادا ہوتی ہے۔' },
    ],
  },

  en: {
    backBtn: 'Back',
    chartBadge: 'Makharij Chart',
    bismillah: 'اَلحَمْدُ لِلَّهِ رَبِّ العٰلَمِينَ وَالصَّلَوٰةُ وَالسَّلَامُ عَلَى سَيِّدِ الْمُرْسَلِينَ أَمَّا بَعْدُ فَأَعُوذُ بِاللَّهِ مِنَ الشَّيْطٰنِ الرَّجِيمِ ط بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ط',
    chartTitle: 'Makharij-ul-Huruf Chart (Points of Articulation)',
    meaningLabel: 'Meaning of Makhraj:',
    meaningText: 'Literally means "exit point". In Tajweed, it refers to the exact anatomical place from which an Arabic letter originates and is pronounced.',
    countText: 'According to Imam Khalil ibn Ahmad and the majority of Tajweed scholars, there are seventeen (17) specific articulation points.',
    tableHeadCategory: 'Region / Category',
    tableHeadHuruf: 'Letters',
    tableHeadTitle: 'Title / Classification',
    tableHeadDesc: 'Articulation Details',
    tableHeadAudio: 'Audio',
    listenBtn: 'Listen',
    closeBtn: 'Close',
    items: [
      { category: 'Throat (Halq)', huruf: 'ء ، ه', title: 'Throat Letters (Halqiyyah)', desc: 'Deepest part of the throat nearest to the chest (Aqsa al-Halq).' },
      { category: 'Throat (Halq)', huruf: 'ع ، ح', title: 'Throat Letters (Halqiyyah)', desc: 'Middle part of the throat (Wasat al-Halq).' },
      { category: 'Throat (Halq)', huruf: 'غ ، خ', title: 'Throat Letters (Halqiyyah)', desc: 'Top part of the throat closest to the mouth (Adna al-Halq).' },
      { category: 'Tongue (Lisan)', huruf: 'ق', title: 'Uvular Letter (Lahwiyyah)', desc: 'Back of the tongue against the soft palate.' },
      { category: 'Tongue (Lisan)', huruf: 'ك', title: 'Uvular Letter (Lahwiyyah)', desc: 'Back of the tongue against the hard palate (just below Qaaf).' },
      { category: 'Tongue (Lisan)', huruf: 'ج ، ش ، ی', title: 'Middle Tongue (Shajariyyah)', desc: 'Middle of the tongue touching the roof of the mouth.' },
      { category: 'Tongue (Lisan)', huruf: 'ض', title: 'Tongue Edge (Hafiyyah)', desc: 'Edge of the tongue touching the upper molars on either side.' },
      { category: 'Tongue (Lisan)', huruf: 'ل', title: 'Tip / Sides (Tarafiyyah)', desc: 'Sides of the front tongue touching the upper gums.' },
      { category: 'Tongue (Lisan)', huruf: 'ن', title: 'Tip / Sides (Tarafiyyah)', desc: 'Tip of the tongue touching the gums of the top front teeth.' },
      { category: 'Tongue (Lisan)', huruf: 'ر', title: 'Tip / Sides (Tarafiyyah)', desc: 'Tip of the tongue with slight roll against upper palate.' },
      { category: 'Tongue (Lisan)', huruf: 'ط ، د ، ت', title: 'Prepallatal (Nit\'iyyah)', desc: 'Tip of the tongue touching the roots of the top two incisors.' },
      { category: 'Tongue (Lisan)', huruf: 'ظ ، ذ ، ث', title: 'Interdental (Lathawiyyah)', desc: 'Tip of the tongue touching the edges of the top two front teeth.' },
      { category: 'Tongue (Lisan)', huruf: 'ص ، ز ، س', title: 'Whistle Letters (Safeeriyyah)', desc: 'Tip of the tongue positioned close to the inner edge of bottom teeth.' },
      { category: 'Lips (Shafatan)', huruf: 'ف', title: 'Labial (Shafawiyyah)', desc: 'Edge of upper front teeth against the wet inner part of bottom lip.' },
      { category: 'Lips (Shafatan)', huruf: 'ب ، م ، و', title: 'Labial (Shafawiyyah)', desc: 'Both lips: Baa (wet part), Meem (dry part), Waw (rounding lips).' },
      { category: 'Oral Cavity (Jauf)', huruf: 'حروفِ مدہ (ا ، و ، ی)', title: 'Empty Space (Jauf)', desc: 'The open empty space of the throat and mouth during prolonged vowels.' },
      { category: 'Nasal Passage (Khaishoom)', huruf: '(Ghunnah)', title: 'Nasal Cavity (Khaishoom)', desc: 'Nasal cavity through which the nasalization (Ghunnah) resonates.' },
    ],
  },

  ar: {
    backBtn: 'رجوع',
    chartBadge: 'مخارج الحروف',
    bismillah: 'اَلحَمْدُ لِلَّهِ رَبِّ العٰلَمِينَ وَالصَّلَوٰةُ وَالسَّلَامُ عَلَى سَيِّدِ الْمُرْسَلِينَ أَمَّا بَعْدُ فَأَعُوذُ بِاللَّهِ مِنَ الشَّيْطٰنِ الرَّجِيمِ ط بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ط',
    chartTitle: 'مَخَارِجُ الْحُرُوفِ الْعَرَبِيَّةِ (Makharij-ul-Huruf)',
    meaningLabel: 'تعريف المخرج:',
    meaningText: 'المخرج لغة: محل الخروج، واصطلاحاً: اسم لمحل خروج الحرف وتمييزه عن غيره.',
    countText: 'المختار عند جمهور علماء التجويد والإمام الخليل بن أحمد الفراهيدي أن مخارج الحروف سبعة عشر (١٧) مخرجاً.',
    tableHeadCategory: 'العضو / المخرج',
    tableHeadHuruf: 'الحروف',
    tableHeadTitle: 'ألقاب الحروف',
    tableHeadDesc: 'بيان المخرج بالتفصيل',
    tableHeadAudio: 'الصوت',
    listenBtn: 'استمع',
    closeBtn: 'إغلاق',
    items: [
      { category: 'الحلق', huruf: 'ء ، ه', title: 'الحروف الحلقية', desc: 'أقصى الحلق (مما يلي الصدر).' },
      { category: 'الحلق', huruf: 'ع ، ح', title: 'الحروف الحلقية', desc: 'وسط الحلق.' },
      { category: 'الحلق', huruf: 'غ ، خ', title: 'الحروف الحلقية', desc: 'أدنى الحلق (مما يلي الفم).' },
      { category: 'اللسان', huruf: 'ق', title: 'الحروف اللهوية', desc: 'أقصى اللسان مع ما يحاذيه من الحنك الأعلى اللحمي.' },
      { category: 'اللسان', huruf: 'ك', title: 'الحروف اللهوية', desc: 'أقصى اللسان أسفل القاف مع الحنك العظمي الصلب.' },
      { category: 'اللسان', huruf: 'ج ، ش ، ی', title: 'الحروف الشجرية', desc: 'وسط اللسان مع ما يحاذيه من الحنك الأعلى.' },
      { category: 'اللسان', huruf: 'ض', title: 'حرف حافي', desc: 'إحدى حافتي اللسان أو كلتيهما مع الأضراس العليا.' },
      { category: 'اللسان', huruf: 'ل', title: 'الحروف الذلقية/الطرفية', desc: 'أدنى حافتي اللسان إلى منتهى طرفه مع لثة الأسنان العليا.' },
      { category: 'اللسان', huruf: 'ن', title: 'الحروف الذلقية/الطرفية', desc: 'طرف اللسان مع لثة الثنايا العليا تحت مخرج اللام.' },
      { category: 'اللسان', huruf: 'ر', title: 'الحروف الذلقية/الطرفية', desc: 'طرف اللسان مع ظهره مائلاً إلى الحنك الأعلى.' },
      { category: 'اللسان', huruf: 'ط ، د ، ت', title: 'الحروف النطعية', desc: 'طرف اللسان مع أصول الثنايا العليا.' },
      { category: 'اللسان', huruf: 'ظ ، ذ ، ث', title: 'الحروف اللثوية', desc: 'طرف اللسان مع أطراف الثنايا العليا.' },
      { category: 'اللسان', huruf: 'ص ، ز ، س', title: 'حروف الصفير', desc: 'طرف اللسان وفوق الثنايا السفلى مع بقاء فرجة.' },
      { category: 'الشفتان', huruf: 'ف', title: 'الحروف الشفوية', desc: 'أطراف الثنايا العليا مع باطن الشفة السفلى.' },
      { category: 'الشفتان', huruf: 'ب ، م ، و', title: 'الحروف الشفوية', desc: 'الشفتان معاً: الباء والميم بانطباق، والواو بانضمام مع بقاء فرجة.' },
      { category: 'الجوف', huruf: 'حروف المد (ا ، و ، ي)', title: 'الحروف الجوفية', desc: 'الخلاء الواقع داخل الحلق والفم.' },
      { category: 'الخيشوم', huruf: '(الغنة)', title: 'مخرج الغنة', desc: 'التجويف الأنفي الداخلي وهو مخرج صوت الغنة المركب في النون والميم.' },
    ],
  },

  hi: {
    backBtn: 'वापस जाएं',
    chartBadge: 'मखारिज चार्ट',
    bismillah: 'اَلحَمْدُ لِلَّهِ رَبِّ العٰلَمِينَ وَالصَّلَوٰةُ وَالسَّلَامُ عَلَى سَيِّدِ الْمُرْسَلِينَ أَمَّا بَعْدُ فَأَعُوذُ بِاللَّهِ مِنَ الشَّيْطٰنِ الرَّجِيمِ ط بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ط',
    chartTitle: 'हुरूफ के मखारिज का नक्शा (Makharij-ul-Huruf Chart)',
    meaningLabel: 'मखरज का अर्थ:',
    meaningText: 'मखरज का शाब्दिक अर्थ "निकलने की जगह" है। तजवीद में जिस जगह से अरबी हर्फ अदा होता है, उसे मखरज कहते हैं।',
    countText: 'इमाम खलील बिन अहमद और अधिकतर विद्वानों के अनुसार मखारिज की कुल संख्या सत्रह (17) है।',
    tableHeadCategory: 'स्थान / श्रेणी',
    tableHeadHuruf: 'हुरूफ',
    tableHeadTitle: 'हुरूफ के नाम',
    tableHeadDesc: 'मखरज का विवरण',
    tableHeadAudio: 'आवाज़',
    listenBtn: 'सुनें',
    closeBtn: 'बंद करें',
    items: [
      { category: 'हलक़ (गला)', huruf: 'ء ، ه', title: 'हुरूफ-ए-हलक़िया', desc: 'हलक़ के सबसे निचले हिस्से (छाती के पास) से।' },
      { category: 'हलक़ (गला)', huruf: 'ع ، ح', title: 'हुरूफ-ए-हलक़िया', desc: 'हलक़ के बीच के हिस्से से।' },
      { category: 'हलक़ (गला)', huruf: 'غ ، خ', title: 'हुरूफ-ए-हलक़िया', desc: 'हलक़ के ऊपरी हिस्से (मुँह के पास) से।' },
      { category: 'ज़बान (जीभ)', huruf: 'ق', title: 'हुरूफ-ए-लहविया', desc: 'ज़बान की जड़ और तालू के नर्म हिस्से से।' },
      { category: 'ज़बान (जीभ)', huruf: 'ك', title: 'हुरूफ-ए-लहविया', desc: 'ज़बान की जड़ और तालू के सख्त हिस्से से।' },
      { category: 'ज़बान (जीभ)', huruf: 'ج ، ش ، ی', title: 'हुरूफ-ए-शजरिया', desc: 'ज़बान का बीच और तालू का बीच।' },
      { category: 'ज़बान (जीभ)', huruf: 'ض', title: 'हर्फ-ए-हाफ़िया', desc: 'ज़बान की करवट और ऊपर की दाढ़ों की जड़।' },
      { category: 'ज़बान (जीभ)', huruf: 'ل', title: 'हुरूफ-ए-तरफ़िया', desc: 'ज़बान का किनारा और मसूढ़ों से।' },
      { category: 'ज़बान (जीभ)', huruf: 'ن', title: 'हुरूफ-ए-तरफ़िया', desc: 'ज़बान का किनारा और ऊपर के दांतों की जड़।' },
      { category: 'ज़बान (जीभ)', huruf: 'ر', title: 'हुरूफ-ए-तरफ़िया', desc: 'ज़बान की नोक और सामने का तालू।' },
      { category: 'ज़बान (जीभ)', huruf: 'ط ، د ، ت', title: 'हुरूफ-ए-नितइया', desc: 'ज़बान की नोक और ऊपर के सामने वाले दो दांतों की जड़।' },
      { category: 'ज़बान (जीभ)', huruf: 'ظ ، ذ ، ث', title: 'हुरूफ-ए-लसवीया', desc: 'ज़बान की नोक और सामने के ऊपर वाले दांतों का अंदरूनी किनारा।' },
      { category: 'ज़बान (जीभ)', huruf: 'ص ، ز ، س', title: 'हुरूफ-ए-सफ़ीरिया', desc: 'ज़बान की नोक और दोनों दांतों के अंदरूनी सिरे।' },
      { category: 'होंठ (शफ़विया)', huruf: 'ف', title: 'हुरूफ-ए-शफ़विया', desc: 'ऊपर के दांतों के सिरे और निचले होंठ का अंदरूनी तर हिस्सा।' },
      { category: 'होंठ (शफ़विया)', huruf: 'ب ، م ، و', title: 'हुरूफ-ए-शफ़विया', desc: 'दोनों होंठ: बा और मीम होंठ मिलाकर, वाव होंठ गोल करके।' },
      { category: 'मुँह का खाली हिस्सा (जौफ)', huruf: 'حروفِ مدہ (ا ، و ، ی)', title: 'जौफ-ए-दहन', desc: 'मुँह और हलक़ का खाली हिस्सा।' },
      { category: 'नाक (खैशूम)', huruf: '(ग़ुन्ना)', title: 'ग़ुन्ना का मखरज', desc: 'नाक की हड्डी से आने वाली गुंजार (ग़ुन्ना)।' },
    ],
  },

  bn: {
    backBtn: 'ফিরে যান',
    chartBadge: 'মাখরাজ চার্ট',
    bismillah: 'اَلحَمْدُ لِلَّهِ رَبِّ العٰلَمِينَ وَالصَّلَوٰةُ وَالسَّلَامُ عَلَى سَيِّدِ الْمُرْسَلِينَ أَمَّا بَعْدُ فَأَعُوذُ بِاللَّهِ مِنَ الشَّيْطٰنِ الرَّجِيمِ ط بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ط',
    chartTitle: 'হুরুফের মাখরাজের চার্ট (Points of Articulation)',
    meaningLabel: 'মাখরাজের অর্থ:',
    meaningText: 'মাখরাজ শব্দের অর্থ "বাহির হওয়ার স্থান"। তাজবীদ শাস্ত্রের পরিভাষায় যে স্থান থেকে হরফ উচ্চারিত হয় তাকে মাখরাজ বলে।',
    countText: 'ইমাম খলিল ইবনে আহমদ ও অধিকাংশ তাজবীদ বিশেষজ্ঞদের মতে মাখরাজের সংখ্যা ১৭টি।',
    tableHeadCategory: 'স্থান / শ্রেণি',
    tableHeadHuruf: 'হরফ',
    tableHeadTitle: 'হরফের উপাধি',
    tableHeadDesc: 'উচ্চারণ স্থানের বিবরণ',
    tableHeadAudio: 'অডিও',
    listenBtn: 'শুনুন',
    closeBtn: 'বন্ধ করুন',
    items: [
      { category: 'হলক্ব (কণ্ঠনালী)', huruf: 'ء ، ه', title: 'হলক্বী হরফ', desc: 'কণ্ঠনালীর নিচের অংশ (বুকের দিক থেকে)।' },
      { category: 'হলক্ব (কণ্ঠনালী)', huruf: 'ع ، ح', title: 'হলক্বী হরফ', desc: 'কণ্ঠনালীর মধ্যখান থেকে।' },
      { category: 'হলক্ব (কণ্ঠনালী)', huruf: 'غ ، خ', title: 'হলক্বী হরফ', desc: 'কণ্ঠনালীর শুরুর অংশ (মুখের নিকটবর্তী)।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ق', title: 'লাহবিয়্যাহ হরফ', desc: 'জিহ্বার গোড়া ও তার বরাবর উপরে নরম তালু।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ك', title: 'লাহবিয়্যাহ হরফ', desc: 'জিহ্বার গোড়া একটু সামনে বাড়িয়ে শক্ত তালুর সঙ্গে।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ج ، ش ، ی', title: 'শাজারিয়্যাহ হরফ', desc: 'জিহ্বার মধ্যভাগ ও তার উপরের তালু।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ض', title: 'হাফিয়্যাহ হরফ', desc: 'জিহ্বার গোড়ার পাশ ও উপরের মাড়ির দাঁত।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ل', title: 'তারফিয়্যাহ হরফ', desc: 'জিহ্বার অগ্রভাগের কিনারা ও উপরের দাঁতের মাড়ি।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ن', title: 'তারফিয়্যাহ হরফ', desc: 'জিহ্বার ডগা ও সামনের দাঁতের গোড়া।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ر', title: 'তারফিয়্যাহ হরফ', desc: 'জিহ্বার ডগার পিঠ ও তালু।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ط ، د ، ت', title: 'নিত\'ইয়্যাহ হরফ', desc: 'জিহ্বার ডগা ও উপরের সামনের দুই দাঁতের গোড়া।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ظ ، ذ ، ث', title: 'লাসাভিয়্যাহ হরফ', desc: 'জিহ্বার ডগা ও সামনের উপরের দুই দাঁতের আগা।' },
      { category: 'জিহ্বা (লিসান)', huruf: 'ص ، ز ، س', title: 'সাফিরিয়্যাহ হরফ', desc: 'জিহ্বার ডগা ও নিচের দাঁতের ভেতরের দিক।' },
      { category: 'ঠোঁট (শাফাতান)', huruf: 'ف', title: 'শাফাবিয়্যাহ হরফ', desc: 'সামনের উপরের দুই দাঁতের আগা ও নিচের ঠোঁটের পেট।' },
      { category: 'ঠোঁট (শাফাতান)', huruf: 'ب ، م ، و', title: 'শাফাবিয়্যাহ হরফ', desc: 'উভয় ঠোঁট: বা ও মীম মিলিয়ে, ওয়াও গোল করে।' },
      { category: 'মুখের ফাঁকা স্থান (জাওফ)', huruf: 'حروفِ مدہ (ا ، و ، ی)', title: 'জাওফে দাহান', desc: 'মুখ ও কণ্ঠের খালি জায়গা।' },
      { category: 'নাক (খাইশূম)', huruf: '(গুন্নাহ)', title: 'গুন্নাহ-এর মাখরাজ', desc: 'নাকের বাঁশি থেকে গুন্নাহ ধ্বনি।' },
    ],
  },

  id: {
    backBtn: 'Kembali',
    chartBadge: 'Bagan Makhraj',
    bismillah: 'اَلحَمْدُ لِلَّهِ رَبِّ العٰلَمِينَ وَالصَّلَوٰةُ وَالسَّلَامُ عَلَى سَيِّدِ الْمُرْسَلِينَ أَمَّا بَعْدُ فَأَعُوذُ بِاللَّهِ مِنَ الشَّيْطٰنِ الرَّجِيمِ ط بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ط',
    chartTitle: 'Bagan Makharijul Huruf (Tempat Keluarnya Huruf)',
    meaningLabel: 'Arti Makhraj:',
    meaningText: 'Secara bahasa berarti "tempat keluar". Dalam ilmu tajwid, makhraj adalah tempat keluarnya huruf saat dibunyikan sehingga membedakannya dengan huruf lain.',
    countText: 'Menurut Imam Khalil bin Ahmad dan mayoritas ulama tajwid, terdapat 17 tempat keluarnya huruf.',
    tableHeadCategory: 'Bagian / Kategori',
    tableHeadHuruf: 'Huruf',
    tableHeadTitle: 'Gelar / Julukan Huruf',
    tableHeadDesc: 'Rincian Tempat Pengucapan',
    tableHeadAudio: 'Audio',
    listenBtn: 'Dengar',
    closeBtn: 'Tutup',
    items: [
      { category: 'Tenggorokan (Halq)', huruf: 'ء ، ه', title: 'Huruf Halqiyyah', desc: 'Tenggorokan bagian bawah terdekat dengan dada (Aqsa al-Halq).' },
      { category: 'Tenggorokan (Halq)', huruf: 'ع ، ح', title: 'Huruf Halqiyyah', desc: 'Tenggorokan bagian tengah (Wasat al-Halq).' },
      { category: 'Tenggorokan (Halq)', huruf: 'غ ، خ', title: 'Huruf Halqiyyah', desc: 'Tenggorokan bagian atas terdekat dengan rongga mulut (Adna al-Halq).' },
      { category: 'Lidah (Lisan)', huruf: 'ق', title: 'Huruf Lahwiyyah', desc: 'Pangkal lidah menyentuh langit-langit lunak bagian atas.' },
      { category: 'Lidah (Lisan)', huruf: 'ك', title: 'Huruf Lahwiyyah', desc: 'Pangkal lidah agak ke depan menyentuh langit-langit keras.' },
      { category: 'Lidah (Lisan)', huruf: 'ج ، ش ، ی', title: 'Huruf Shajariyyah', desc: 'Tengah lidah menyentuh langit-langit atas.' },
      { category: 'Lidah (Lisan)', huruf: 'ض', title: 'Huruf Hafiyyah', desc: 'Tepi lidah menyentuh gigi geraham atas.' },
      { category: 'Lidah (Lisan)', huruf: 'ل', title: 'Huruf Tarafiyyah', desc: 'Ujung tepi lidah menyentuh gusi gigi atas.' },
      { category: 'Lidah (Lisan)', huruf: 'ن', title: 'Huruf Tarafiyyah', desc: 'Ujung lidah menempel pada gusi gigi seri atas.' },
      { category: 'Lidah (Lisan)', huruf: 'ر', title: 'Huruf Tarafiyyah', desc: 'Punggung ujung lidah bergetar sedikit menyentuh langit-langit atas.' },
      { category: 'Lidah (Lisan)', huruf: 'ط ، د ، ت', title: 'Huruf Nit\'iyyah', desc: 'Ujung lidah menempel pada pangkal gigi seri atas.' },
      { category: 'Lidah (Lisan)', huruf: 'ظ ، ذ ، ث', title: 'Huruf Lathawiyyah', desc: 'Ujung lidah menyentuh ujung gigi seri atas.' },
      { category: 'Lidah (Lisan)', huruf: 'ص ، ز ، س', title: 'Huruf Safiriyyah', desc: 'Ujung lidah berada di dekat pangkal gigi seri bawah.' },
      { category: 'Bibir (Syafatan)', huruf: 'ف', title: 'Huruf Syafawiyyah', desc: 'Ujung gigi seri atas menyentuh bagian dalam bibir bawah.' },
      { category: 'Bibir (Syafatan)', huruf: 'ب ، م ، و', title: 'Huruf Syafawiyyah', desc: 'Kedua bibir: Ba dan Mim dirapatkan, Waw dimonyongkan/dibulatkan.' },
      { category: 'Rongga Mulut (Jauf)', huruf: 'حروفِ مدہ (ا ، و ، ی)', title: 'Al-Jauf', desc: 'Rongga kosong mulut dan tenggorokan untuk huruf mad.' },
      { category: 'Pangkal Hidung (Khaisyum)', huruf: '(Ghunnah)', title: 'Al-Khaisyum', desc: 'Pangkal rongga hidung tempat dengung (ghunnah).' },
    ],
  },

  tr: {
    backBtn: 'Geri',
    chartBadge: 'Mahreç Tablosu',
    bismillah: 'اَلحَمْدُ لِلَّهِ رَبِّ العٰلَمِينَ وَالصَّلَوٰةُ وَالسَّلَامُ عَلَى سَيِّدِ الْمُرْسَلِينَ أَمَّا بَعْدُ فَأَعُوذُ بِاللَّهِ مِنَ الشَّيْطٰنِ الرَّجِيمِ ط بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ط',
    chartTitle: 'Mahreç Tablosu (Harflerin Çıkış Yerleri)',
    meaningLabel: 'Mahreç Tanımı:',
    meaningText: 'Kelime anlamı "çıkış yeri"dir. Tecvid ıstılahında harfin sesinin çıktığı ve diğer harflerden ayrıldığı anatomik yere denir.',
    countText: 'İmam Halil bin Ahmed ve cumhur tecvid ulemasına göre toplam mahreç sayısı 17\'dir.',
    tableHeadCategory: 'Bölge / Kategori',
    tableHeadHuruf: 'Harfler',
    tableHeadTitle: 'Harf Unvanları',
    tableHeadDesc: 'Çıkış Yeri Detayı',
    tableHeadAudio: 'Ses',
    listenBtn: 'Dinle',
    closeBtn: 'Kapat',
    items: [
      { category: 'Boğaz (Halk)', huruf: 'ء ، ه', title: 'Halkiyye Harfleri', desc: 'Boğazın göğse en yakın alt kısmı (Aksâ\'l-Halk).' },
      { category: 'Boğaz (Halk)', huruf: 'ع ، ح', title: 'Halkiyye Harfleri', desc: 'Boğazın orta kısmı (Vasatü\'l-Halk).' },
      { category: 'Boğaz (Halk)', huruf: 'غ ، خ', title: 'Halkiyye Harfleri', desc: 'Boğazın ağza en yakın üst kısmı (Ednâ\'l-Halk).' },
      { category: 'Dil (Lisân)', huruf: 'ق', title: 'Leheviyye Harfi', desc: 'Dil kökünün yumuşak damağa değmesiyle.' },
      { category: 'Dil (Lisân)', huruf: 'ك', title: 'Leheviyye Harfi', desc: 'Dil kökünün sert damağa değmesiyle (Kaf\'ın biraz altı).' },
      { category: 'Dil (Lisân)', huruf: 'ج ، ش ، ی', title: 'Şeceriyye Harfleri', desc: 'Dilin ortasının üst damağa temas etmesiyle.' },
      { category: 'Dil (Lisân)', huruf: 'ض', title: 'Hâfiyye Harfi', desc: 'Dilin yan tarafının üst azı dişlerine değmesiyle.' },
      { category: 'Dil (Lisân)', huruf: 'ل', title: 'Tarafiyye Harfi', desc: 'Dil ucunun yanlarının üst diş etlerine değmesiyle.' },
      { category: 'Dil (Lisân)', huruf: 'ن', title: 'Tarafiyye Harfi', desc: 'Dil ucunun üst ön diş etlerine değmesiyle.' },
      { category: 'Dil (Lisân)', huruf: 'ر', title: 'Tarafiyye Harfi', desc: 'Dil ucunun sırtıyla üst damağa temas etmesiyle.' },
      { category: 'Dil (Lisân)', huruf: 'ط ، د ، ت', title: 'Nıt\'ıyye Harfleri', desc: 'Dil ucunun üst ön dişlerin köklerine değmesiyle.' },
      { category: 'Dil (Lisân)', huruf: 'ظ ، ذ ، ث', title: 'Liseviyye Harfleri', desc: 'Dil ucunun üst ön dişlerin uçlarına değmesiyle.' },
      { category: 'Dil (Lisân)', huruf: 'ص ، ز ، س', title: 'Safîriyye Harfleri', desc: 'Dil ucunun alt dişlerin iç yüzeyine yaklaşmasıyla.' },
      { category: 'Dudaklar (Şefetân)', huruf: 'ف', title: 'Şefeviyye Harfi', desc: 'Üst ön dişlerin uçlarının alt dudağın iç kısmına değmesiyle.' },
      { category: 'Dudaklar (Şefetân)', huruf: 'ب ، م ، و', title: 'Şefeviyye Harfleri', desc: 'İki dudak: Ba ve Mim birbirine kapanarak, Vav büzülerek.' },
      { category: 'Ağız Boşluğu (Cevf)', huruf: 'حروفِ مدہ (ا ، و ، ی)', title: 'Cevf', desc: 'Boğaz ve ağız içindeki açık boşluktan uzatılarak.' },
      { category: 'Geniz (Hayşûm)', huruf: '(Gunne)', title: 'Hayşûm', desc: 'Burun boşluğundan gelen geniz sesi (Gunne).' },
    ],
  },

  fr: {
    backBtn: 'Retour',
    chartBadge: 'Tableau des Makharij',
    bismillah: 'اَلحَمْدُ لِلَّهِ رَبِّ العٰلَمِينَ وَالصَّلَوٰةُ وَالسَّلَامُ عَلَى سَيِّدِ الْمُرْسَلِينَ أَمَّا بَعْدُ فَأَعُوذُ بِاللَّهِ مِنَ الشَّيْطٰنِ الرَّجِيمِ ط بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ط',
    chartTitle: 'Tableau des Points d\'Articulation (Makharij-ul-Huruf)',
    meaningLabel: 'Sens de Makhraj :',
    meaningText: 'Signifie littéralement "point de sortie". En Tajweed, il désigne l\'endroit anatomique précis d\'où provient et se prononce une lettre arabe.',
    countText: 'Selon l\'Imam Khalil ibn Ahmad et la majorité des savants de Tajweed, il y a dix-sept (17) points d\'articulation précis.',
    tableHeadCategory: 'Région / Catégorie',
    tableHeadHuruf: 'Lettres',
    tableHeadTitle: 'Titre / Classification',
    tableHeadDesc: 'Détails de l\'articulation',
    tableHeadAudio: 'Audio',
    listenBtn: 'Écouter',
    closeBtn: 'Fermer',
    items: [
      { category: 'Gorge (Halq)', huruf: 'ء ، ه', title: 'Lettres de la Gorge (Halqiyyah)', desc: 'Partie la plus profonde de la gorge près de la poitrine (Aqsa al-Halq).' },
      { category: 'Gorge (Halq)', huruf: 'ع ، ح', title: 'Lettres de la Gorge (Halqiyyah)', desc: 'Partie médiane de la gorge (Wasat al-Halq).' },
      { category: 'Gorge (Halq)', huruf: 'غ ، خ', title: 'Lettres de la Gorge (Halqiyyah)', desc: 'Partie supérieure de la gorge proche de la bouche (Adna al-Halq).' },
      { category: 'Langue (Lisan)', huruf: 'ق', title: 'Lettre Uvulaire (Lahwiyyah)', desc: 'Arrière de la langue contre le palais mou.' },
      { category: 'Langue (Lisan)', huruf: 'ك', title: 'Lettre Uvulaire (Lahwiyyah)', desc: 'Arrière de la langue contre le palais dur (juste sous Qaaf).' },
      { category: 'Langue (Lisan)', huruf: 'ج ، ش ، ی', title: 'Milieu de la Langue (Shajariyyah)', desc: 'Milieu de la langue touchant le palais supérieur.' },
      { category: 'Langue (Lisan)', huruf: 'ض', title: 'Bord de la Langue (Hafiyyah)', desc: 'Bord de la langue contre les molaires supérieures.' },
      { category: 'Langue (Lisan)', huruf: 'ل', title: 'Bouts / Côtés (Tarafiyyah)', desc: 'Côtés de la langue avant touchant les gencives supérieures.' },
      { category: 'Langue (Lisan)', huruf: 'ن', title: 'Bouts / Côtés (Tarafiyyah)', desc: 'Pointe de la langue touchant les gencives des incisives supérieures.' },
      { category: 'Langue (Lisan)', huruf: 'ر', title: 'Bouts / Côtés (Tarafiyyah)', desc: 'Pointe de la langue roulant légèrement contre le palais.' },
      { category: 'Langue (Lisan)', huruf: 'ط ، د ، ت', title: 'Prépallatales (Nit\'iyyah)', desc: 'Pointe de la langue touchant la base des deux incisives supérieures.' },
      { category: 'Langue (Lisan)', huruf: 'ظ ، ذ ، ث', title: 'Interdentales (Lathawiyyah)', desc: 'Pointe de la langue touchant le bord des deux incisives supérieures.' },
      { category: 'Langue (Lisan)', huruf: 'ص ، ز ، س', title: 'Lettres Sifflantes (Safeeriyyah)', desc: 'Pointe de la langue proche du bord intérieur des dents inférieures.' },
      { category: 'Lèvres (Shafatan)', huruf: 'ف', title: 'Labiales (Shafawiyyah)', desc: 'Bord des incisives supérieures contre l\'intérieur humide de la lèvre inférieure.' },
      { category: 'Lèvres (Shafatan)', huruf: 'ب ، م ، و', title: 'Labiales (Shafawiyyah)', desc: 'Les deux lèvres : Baa et Meem en les fermant, Waw en les arrondissant.' },
      { category: 'Cavité Buccale (Jauf)', huruf: 'حروفِ مدہ (ا ، و ، ی)', title: 'Espace Vide (Jauf)', desc: 'L\'espace vide de la gorge et de la bouche lors des voyelles longues.' },
      { category: 'Cavité Nasale (Khaishoom)', huruf: '(Ghunnah)', title: 'Cavité Nasale (Khaishoom)', desc: 'Cavité nasale produisant la résonance nasale (Ghunnah).' },
    ],
  },
};

export const getMakharijLocalization = (lang?: LanguageCode): MakharijModalTexts => {
  return MAKHARIJ_LOCALIZATION[lang || 'ur'] || MAKHARIJ_LOCALIZATION.ur;
};
