import { LanguageCode } from '../types';

export interface MutaharrikatGameTexts {
  headerTitle: string;
  headerSubtitle: string;
  backBtn: string;
  score: string;
  coins: string;
  streak: string;
  best: string;
  level: string;
  level1: string;
  level2: string;
  level3: string;
  level4: string;
  timerActive: string;
  timerChallenge: string;
  ruleTitle: string;
  ruleDesc: string;
  timeRemaining: string;
  answerQuickly: string;
  listenPrompt: string;
  listenAgain: string;
  breakdownTitle: string;
  listenBreakdownFlow: string;
  skipNewWord: string;
  backToBoard: string;
  voicePracticeTitle: string;
  voicePracticeDesc: (target: string, breakdown: string) => string;
  voiceRecording: string;
  voiceButton: string;
  voicePromptFeedback: string;
  voiceSuccessFeedback: (target: string) => string;
  tryAgainBtn: string;
  wrongToastTitle: string;
  wrongToastDesc: (chosen: string, correct: string, breakdown: string) => string;
  correctToastTitle: string;
  correctToastDesc: string;
}

export const MUTAHARRIKAT_LOCALIZATION: Record<LanguageCode, MutaharrikatGameTexts> = {
  ur: {
    headerTitle: 'صوتی و بصری گیم: ۲ حرفی و ۳ حرفی متحرک کلمات 🎯',
    headerSubtitle: 'دَرَ، زَرَ، عَدَ اور وَزَنَ، وَرَدَ، أَمَرَ جیسے ۲ و ۳ حرفی متحرک کلمات کو بغیر کھینچے روانی سے پڑھنے کا کھیل',
    backBtn: 'واپسی',
    score: 'اسکور',
    coins: 'کوائنز',
    streak: 'روانی اسٹریک',
    best: 'بہترین',
    level: 'لیول',
    level1: 'لیول ۱: مفردات (بَ، بِ، بُ)',
    level2: 'لیول ۲: ۲ حرفی کلمات (دَرَ، زَرَ، عَدَ...)',
    level3: 'لیول ۳: ۳ حرفی کلمات (وَزَنَ، وَرَدَ...)',
    level4: 'لیول ۴: ۳ حرفی سپیڈ رَش (۵s)',
    timerActive: 'روانی ٹائمر (۵ سیکنڈ آن)',
    timerChallenge: 'ٹائمر چیلنج آن کریں',
    ruleTitle: '💡 اہم تجویدی قاعدہ (۲ و ۳ حرفی متحرک کلمات):',
    ruleDesc: 'تمام حرکات (زبر، زیر، پیش) والے ۲ اور ۳ حرفی کلمات کو بغیر کھینچے اور بغیر جھٹکا دیے روانی سے ملا کر پڑھیں۔',
    timeRemaining: 'روانی وقت:',
    answerQuickly: 'جلد جواب دیجئے!',
    listenPrompt: 'قاری کی آواز کو بغور سن کر درست ۳ حرفی کلمہ چنیں:',
    listenAgain: 'آواز دوبارہ سنیں (🔊)',
    breakdownTitle: 'حروفی تحليل (حرف بہ حرف):',
    listenBreakdownFlow: 'روانی جوڑ سنیں',
    skipNewWord: 'نیا ۳ حرفی کلمہ (Skip)',
    backToBoard: 'بورڈ پر واپس جائیں',
    voicePracticeTitle: 'خود ادا کر کے دیکھئے (Voice Practice):',
    voicePracticeDesc: (target, breakdown) => `مائیک دبائیں اور "${target}" ${breakdown ? `(${breakdown})` : ''} بول کر اپنی آواز جانیے۔`,
    voiceRecording: 'آواز ریکارڈ ہو رہی ہے...',
    voiceButton: 'مائیک سے بولو',
    voicePromptFeedback: 'براہ کرم مائیک کے قریب بغیر کھینچے روانی سے تلفظ فرمائیں...',
    voiceSuccessFeedback: (target) => `ماشاء اللہ! آپ کا تلفظ "${target}" بالکل صحیح، تیز اور روانی کے ساتھ تھا! ✨`,
    tryAgainBtn: 'اگلا کلمہ آزمائیں ←',
    wrongToastTitle: 'دوبارہ کوشش کریں! ❌',
    wrongToastDesc: (chosen, correct, breakdown) => `آپ نے "${chosen}" پر کلک کیا۔ صحیح جواب "${correct}" ${breakdown ? `(${breakdown})` : ''} ہے۔ حرکات کو بغیر کھینچے روانی سے پڑھیں!`,
    correctToastTitle: 'ماشاء اللہ! درست جواب 🎉',
    correctToastDesc: 'بہت خوب! آپ نے متحرک کلمہ بغیر کھینچے بالکل صحیح منتخب کیا۔',
  },
  en: {
    headerTitle: 'Audio-Visual Game: 2 & 3 Letter Vowel Words 🎯',
    headerSubtitle: 'Practice reading short vowel compounds smoothly without stretching or jerking',
    backBtn: 'Back',
    score: 'Score',
    coins: 'Coins',
    streak: 'Fluency Streak',
    best: 'Best',
    level: 'Level',
    level1: 'Level 1: Single (Ba, Bi, Bu)',
    level2: 'Level 2: 2-Letter Words (Dara, Zara...)',
    level3: 'Level 3: 3-Letter Words (Wazana, Warada...)',
    level4: 'Level 4: Speed Rush (5s)',
    timerActive: 'Fluency Timer (5s Active)',
    timerChallenge: 'Enable Timer Challenge',
    ruleTitle: '💡 Key Tajweed Rule (Short Vowels / Harakat):',
    ruleDesc: 'Read all vowel signs (Fathah, Kasrah, Dammah) smoothly and promptly without elongating or jerking.',
    timeRemaining: 'Time Left:',
    answerQuickly: 'Answer promptly!',
    listenPrompt: 'Listen carefully to the Qari and select the matching word:',
    listenAgain: 'Listen Again (🔊)',
    breakdownTitle: 'Letter Breakdown:',
    listenBreakdownFlow: 'Listen Combined',
    skipNewWord: 'New Word (Skip)',
    backToBoard: 'Back to Board',
    voicePracticeTitle: 'Voice Pronunciation Practice:',
    voicePracticeDesc: (target, breakdown) => `Press the mic and recite "${target}" ${breakdown ? `(${breakdown})` : ''} to check your fluency.`,
    voiceRecording: 'Recording voice...',
    voiceButton: 'Speak into Mic',
    voicePromptFeedback: 'Please recite clearly near the microphone without stretching...',
    voiceSuccessFeedback: (target) => `MashaAllah! Your pronunciation of "${target}" was accurate and smooth! ✨`,
    tryAgainBtn: 'Try Next Word ←',
    wrongToastTitle: 'Try Again! ❌',
    wrongToastDesc: (chosen, correct, breakdown) => `You selected "${chosen}". The correct word is "${correct}" ${breakdown ? `(${breakdown})` : ''}. Read promptly without stretching!`,
    correctToastTitle: 'MashaAllah! Correct Answer 🎉',
    correctToastDesc: 'Excellent! You identified the short vowel word correctly.',
  },
  ar: {
    headerTitle: 'اللعبة الصوتية والمرئية: كلمات الحركات الثنائية والثلاثية 🎯',
    headerSubtitle: 'تدريب على قراءة الكلمات المتحركة دون مد ولا تمطيط وبسرعة مناسبة',
    backBtn: 'رجوع',
    score: 'النقاط',
    coins: 'العملات',
    streak: 'سلسلة الطلاقة',
    best: 'الأفضل',
    level: 'المستوى',
    level1: 'المستوى ١: الحروف المفردة (بَ، بِ، بُ)',
    level2: 'المستوى ٢: كلمات ثنائية (دَرَ، زَرَ، عَدَ)',
    level3: 'المستوى ٣: كلمات ثلاثية (وَزَنَ، وَرَدَ)',
    level4: 'المستوى ٤: تحدي السرعة (٥ ثوانٍ)',
    timerActive: 'مؤقت الطلاقة (٥ ثوانٍ نشط)',
    timerChallenge: 'تفعيل تحدي المؤقت',
    ruleTitle: '💡 قاعدة تجويدية هامة (الحركات الثلاث):',
    ruleDesc: 'تُقرأ الحركات (الفتحة والكسرة والضمة) بسرعة وطلاقة دون مد الحرف ولا سكت.',
    timeRemaining: 'الوقت المتبقي:',
    answerQuickly: 'أجب بسرعة!',
    listenPrompt: 'استمع إلى القارئ بدقة واختر الكلمة الصحيحة المطابقة:',
    listenAgain: 'إعادة الاستماع (🔊)',
    breakdownTitle: 'التحليل الهجائي (حرفاً حرفاً):',
    listenBreakdownFlow: 'استماع الدرج والوصل',
    skipNewWord: 'كلمة جديدة (تخطي)',
    backToBoard: 'الرجوع إلى اللوحة',
    voicePracticeTitle: 'التدريب الصوتي بالنطق:',
    voicePracticeDesc: (target, breakdown) => `اضغط على الميكروفون وانطق "${target}" ${breakdown ? `(${breakdown})` : ''}.`,
    voiceRecording: 'جارٍ تسجيل الصوت...',
    voiceButton: 'تحدث في الميكروفون',
    voicePromptFeedback: 'يرجى النطق بوضوح دون مد بالقرب من الميكروفون...',
    voiceSuccessFeedback: (target) => `ما شاء الله! نطقك لكلمة "${target}" صحيح وسريع ومتقن! ✨`,
    tryAgainBtn: 'جرّب الكلمة التالية ←',
    wrongToastTitle: 'حاول مرة أخرى! ❌',
    wrongToastDesc: (chosen, correct, breakdown) => `لقد اخترت "${chosen}". الكلمة الصحيحة هي "${correct}" ${breakdown ? `(${breakdown})` : ''}. اقرأ بالحركات دون مد!`,
    correctToastTitle: 'ما شاء الله! إجابة صحيحة 🎉',
    correctToastDesc: 'أحسنت! لقد تمكنت من تحديد الكلمة المتحركة بدقة تامة.',
  },
  hi: {
    headerTitle: 'ऑडियो-विज़ुअल गेम: २ व ३ अक्षरी मुतह़र्रिक शब्द 🎯',
    headerSubtitle: 'दरा, ज़रा और वज़ना जैसे शब्दों को बिना खींचे रवानगी से पढ़ने का खेल',
    backBtn: 'वापसी',
    score: 'स्कोर',
    coins: 'सिक्के',
    streak: 'रवानगी स्ट्रीक',
    best: 'सर्वश्रेष्ठ',
    level: 'स्तर',
    level1: 'लेवल १: मुफ़्रदात (बَ، بِ، بُ)',
    level2: 'लेवल २: २ अक्षरी शब्द (دَرَ، زَرَ، عَدَ)',
    level3: 'लेवल ३: ३ अक्षरी शब्द (وَزَنَ، وَرَدَ)',
    level4: 'लेवल ४: स्पीड रश (५ सेकंड)',
    timerActive: 'टाइमर सक्रिय (५ सेकंड)',
    timerChallenge: 'टाइमर चुनौती चालू करें',
    ruleTitle: '💡 अहम तजवीदी नियम (हरकात):',
    ruleDesc: 'ज़बर, ज़ेर, पेश वाले शब्दों को बिना खींचे और बिना झटका दिए रवानगी से मिलाकर पढ़ें।',
    timeRemaining: 'बचा समय:',
    answerQuickly: 'जल्दी उत्तर दें!',
    listenPrompt: 'क़ारी की आवाज़ सुनकर सही शब्द चुनें:',
    listenAgain: 'आवाज़ दोबारा सुनें (🔊)',
    breakdownTitle: 'अक्षर विश्लेषण (हिज्जे):',
    listenBreakdownFlow: 'रवानगी से सुनें',
    skipNewWord: 'नया शब्द (छोड़ें)',
    backToBoard: 'बोर्ड पर वापस जाएं',
    voicePracticeTitle: 'आवाज़ से पढ़ने का अभ्यास:',
    voicePracticeDesc: (target, breakdown) => `माइक दबाएं और "${target}" ${breakdown ? `(${breakdown})` : ''} बोलकर जांचें।`,
    voiceRecording: 'आवाज़ रिकॉर्ड हो रही है...',
    voiceButton: 'माइक से बोलें',
    voicePromptFeedback: 'कृपया माइक के पास बिना खींचे रवानगी से पढ़ें...',
    voiceSuccessFeedback: (target) => `माशाअल्लाह! "${target}" का आपका उच्चारण बिल्कुल सही और रवां था! ✨`,
    tryAgainBtn: 'अगला शब्द आजमाएं ←',
    wrongToastTitle: 'दोबारा प्रयास करें! ❌',
    wrongToastDesc: (chosen, correct, breakdown) => `आपने "${chosen}" चुना। सही शब्द "${correct}" ${breakdown ? `(${breakdown})` : ''} है। बिना खींचे रवानगी से पढ़ें!`,
    correctToastTitle: 'माशाअल्लाह! सही उत्तर 🎉',
    correctToastDesc: 'बहुत खूब! आपने सही मुतह़र्रिक शब्द चुना।',
  },
  bn: {
    headerTitle: 'অডিও-ভিজ্যুয়াল গেম: ২ ও ৩ হরফের মুতাহাররিক শব্দ 🎯',
    headerSubtitle: 'টান ছাড়া মসৃণভাবে হরকতের শব্দ পড়ার মজাদার অনুশীলন',
    backBtn: 'ফিরে যান',
    score: 'স্কোর',
    coins: 'কয়েন',
    streak: 'অনর্গল স্ট্রিক',
    best: 'সেরা',
    level: 'লেভেল',
    level1: 'লেভেল ১: একক হরফ (বা, বি, বু)',
    level2: 'লেভেল ২: ২ হরফের শব্দ (দারা, জারা...)',
    level3: 'লেভেল ৩: ৩ হরফের শব্দ (ওয়াযানা, ওয়ারাদা...)',
    level4: 'লেভেল ৪: স্পিড রাশ (৫ সে.)',
    timerActive: 'টাইমার সক্রিয় (৫ সে.)',
    timerChallenge: 'টাইমার চ্যালেঞ্জ চালু করুন',
    ruleTitle: '💡 জরুরি তাজবীদ নিয়ম (হরকত):',
    ruleDesc: 'যবর, যের ও পেশযুক্ত হরফগুলোকে না টেনে এবং ধাক্কা না দিয়ে দ্রুত ও সাবলীলভাবে পড়ুন।',
    timeRemaining: 'বাকি সময়:',
    answerQuickly: 'দ্রুত উত্তর দিন!',
    listenPrompt: 'ক্বারীর কণ্ঠ মনোযোগ দিয়ে শুনে সঠিক শব্দটি নির্বাচন করুন:',
    listenAgain: 'পুনরায় শুনুন (🔊)',
    breakdownTitle: 'হরফ বিশ্লেষণ:',
    listenBreakdownFlow: 'মিলিয়ে শুনুন',
    skipNewWord: 'পরবর্তী শব্দ (স্কিপ)',
    backToBoard: 'বোর্ডে ফিরে যান',
    voicePracticeTitle: 'কণ্ঠস্বরে উচ্চারণের অনুশীলন:',
    voicePracticeDesc: (target, breakdown) => `মাইকে চাপুন এবং "${target}" ${breakdown ? `(${breakdown})` : ''} স্পষ্টভাবে বলুন।`,
    voiceRecording: 'কণ্ঠ রেকর্ড হচ্ছে...',
    voiceButton: 'মাইকে বলুন',
    voicePromptFeedback: 'অনুগ্রহ করে মাইকের কাছে টান ছাড়া সাবলীলভাবে উচ্চারণ করুন...',
    voiceSuccessFeedback: (target) => `মাশাআল্লাহ! "${target}" শব্দের আপনার উচ্চারণটি চমৎকার ও নির্ভুল ছিল! ✨`,
    tryAgainBtn: 'পরের শব্দ চেষ্টা করুন ←',
    wrongToastTitle: 'আবার চেষ্টা করুন! ❌',
    wrongToastDesc: (chosen, correct, breakdown) => `আপনি "${chosen}" ক্লিক করেছেন। সঠিক উত্তর "${correct}" ${breakdown ? `(${breakdown})` : ''}। না টেনে সাবলীলভাবে পড়ুন!`,
    correctToastTitle: 'মাশাআল্লাহ! সঠিক উত্তর 🎉',
    correctToastDesc: 'চমৎকার! আপনি সঠিক শব্দটি চিনতে পেরেছেন।',
  },
  id: {
    headerTitle: 'Game Audio-Visual: Kata Berharakat 2 & 3 Huruf 🎯',
    headerSubtitle: 'Latihan membaca kata berharakat lancar tanpa dipanjangkan atau disentak',
    backBtn: 'Kembali',
    score: 'Skor',
    coins: 'Koin',
    streak: 'Runtutan Lancar',
    best: 'Terbaik',
    level: 'Level',
    level1: 'Level 1: Tunggal (Ba, Bi, Bu)',
    level2: 'Level 2: Kata 2 Huruf (Dara, Zara...)',
    level3: 'Level 3: Kata 3 Huruf (Wazana, Warada...)',
    level4: 'Level 4: Kecepatan Kilat (5 dtk)',
    timerActive: 'Timer Kelancaran (5 detik)',
    timerChallenge: 'Aktifkan Tantangan Timer',
    ruleTitle: '💡 Kaidah Tajwid Penting (Harakat):',
    ruleDesc: 'Bacalah harakat (fathah, kasrah, dammah) secara lancar dan cepat tanpa memanjangkan atau menghentak.',
    timeRemaining: 'Sisa Waktu:',
    answerQuickly: 'Jawab segera!',
    listenPrompt: 'Dengarkan bacaan Qari dengan saksama dan pilih kata yang benar:',
    listenAgain: 'Dengarkan Lagi (🔊)',
    breakdownTitle: 'Penguraian Huruf:',
    listenBreakdownFlow: 'Dengarkan Gabungan',
    skipNewWord: 'Kata Baru (Lewati)',
    backToBoard: 'Kembali ke Papan',
    voicePracticeTitle: 'Latihan Pelafalan Suara:',
    voicePracticeDesc: (target, breakdown) => `Tekan mikrofon dan ucapkan "${target}" ${breakdown ? `(${breakdown})` : ''}.`,
    voiceRecording: 'Merekam suara...',
    voiceButton: 'Bicara di Mic',
    voicePromptFeedback: 'Silakan lafalkan dengan jelas dekat mikrofon tanpa memanjangkan...',
    voiceSuccessFeedback: (target) => `Maa Syaa Allah! Pelafalan "${target}" Anda sangat tepat dan lancar! ✨`,
    tryAgainBtn: 'Coba Kata Berikutnya ←',
    wrongToastTitle: 'Coba Lagi! ❌',
    wrongToastDesc: (chosen, correct, breakdown) => `Anda memilih "${chosen}". Kata yang benar adalah "${correct}" ${breakdown ? `(${breakdown})` : ''}. Baca lancar tanpa memanjangkan!`,
    correctToastTitle: 'Maa Syaa Allah! Jawaban Benar 🎉',
    correctToastDesc: 'Bagus sekali! Anda berhasil memilih kata berharakat dengan benar.',
  },
  tr: {
    headerTitle: 'Görsel ve İşitsel Oyun: 2 ve 3 Harfli Harekeli Kelimeler 🎯',
    headerSubtitle: 'Harekeli kelimeleri uzatmadan ve sektirmeden akıcı okuma pratiği',
    backBtn: 'Geri',
    score: 'Puan',
    coins: 'Altın',
    streak: 'Akıcılık Serisi',
    best: 'En İyi',
    level: 'Seviye',
    level1: 'Seviye 1: Tek Harfler (Be, Bi, Bu)',
    level2: 'Seviye 2: 2 Harfli Kelimeler (Dere, Zere...)',
    level3: 'Seviye 3: 3 Harfli Kelimeler (Vezene, Verede...)',
    level4: 'Seviye 4: Hız Modu (5 sn)',
    timerActive: 'Süre Sayacı (5 sn Aktif)',
    timerChallenge: 'Süreli Meydan Okumayı Aç',
    ruleTitle: '💡 Önemli Tecvid Kuralı (Harekeler):',
    ruleDesc: 'Üstün, esre ve ötreli harfleri uzatmadan ve tutmadan seri bir şekilde birleştirerek okuyunuz.',
    timeRemaining: 'Kalan Süre:',
    answerQuickly: 'Hemen cevaplayın!',
    listenPrompt: 'Kariyi dikkatlice dinleyip doğru kelimeyi seçin:',
    listenAgain: 'Tekrar Dinle (🔊)',
    breakdownTitle: 'Harf Harf Ayrıştırma:',
    listenBreakdownFlow: 'Akıcı Birleşimi Dinle',
    skipNewWord: 'Yeni Kelime (Geç)',
    backToBoard: 'Panoya Geri Dön',
    voicePracticeTitle: 'Sesli Telaffuz Alıştırması:',
    voicePracticeDesc: (target, breakdown) => `Mikrofona basıp "${target}" ${breakdown ? `(${breakdown})` : ''} söyleyerek deneyin.`,
    voiceRecording: 'Ses kaydediliyor...',
    voiceButton: 'Mikrofonla Söyle',
    voicePromptFeedback: 'Lütfen mikrofona yakın şekilde uzatmadan akıcı okuyun...',
    voiceSuccessFeedback: (target) => `Maşallah! "${target}" telaffuzunuz çok doğru ve akıcıydı! ✨`,
    tryAgainBtn: 'Sonraki Kelimeyi Dene ←',
    wrongToastTitle: 'Tekrar Deneyin! ❌',
    wrongToastDesc: (chosen, correct, breakdown) => `"${chosen}" seçtiniz. Doğru cevap "${correct}" ${breakdown ? `(${breakdown})` : ''}. Harekeleri uzatmadan okuyunuz!`,
    correctToastTitle: 'Maşallah! Doğru Cevap 🎉',
    correctToastDesc: 'Harika! Harekeli kelimeyi doğru tanıdınız.',
  },
  fr: {
    headerTitle: 'Jeu Audio-Visuel : Mots Vocalisés à 2 et 3 Lettres 🎯',
    headerSubtitle: 'Entraînez-vous à lire les voyelles brèves avec fluidité sans allongement indu',
    backBtn: 'Retour',
    score: 'Score',
    coins: 'Pièces',
    streak: 'Série Fluide',
    best: 'Meilleur',
    level: 'Niveau',
    level1: 'Niveau 1 : Lettres Isolées (Ba, Bi, Bou)',
    level2: 'Niveau 2 : Mots de 2 Lettres (Dara, Zara...)',
    level3: 'Niveau 3 : Mots de 3 Lettres (Wazana, Warada...)',
    level4: 'Niveau 4 : Défi Vitesse (5s)',
    timerActive: 'Chronomètre (5s Actif)',
    timerChallenge: 'Activer le Défi Chrono',
    ruleTitle: '💡 Règle de Tajweed Importante (Les Harakat) :',
    ruleDesc: 'Lisez les voyelles brèves (Fathah, Kasrah, Dammah) rapidement sans allongement ni coupure saccadée.',
    timeRemaining: 'Temps Restant :',
    answerQuickly: 'Répondez vite !',
    listenPrompt: 'Écoutez attentivement le Récitateur et choisissez le mot correspondant :',
    listenAgain: 'Réécouter (🔊)',
    breakdownTitle: 'Décomposition Lettre par Lettre :',
    listenBreakdownFlow: 'Écouter l\'Enchaînement',
    skipNewWord: 'Nouveau Mot (Passer)',
    backToBoard: 'Retour au Tableau',
    voicePracticeTitle: 'Entraînement Vocal de Prononciation :',
    voicePracticeDesc: (target, breakdown) => `Appuyez sur le micro et récitez "${target}" ${breakdown ? `(${breakdown})` : ''}.`,
    voiceRecording: 'Enregistrement en cours...',
    voiceButton: 'Parler au Micro',
    voicePromptFeedback: 'Veuillez réciter clairement près du micro sans étirer la voix...',
    voiceSuccessFeedback: (target) => `Macha'Allah ! Votre prononciation de "${target}" était fluide et exacte ! ✨`,
    tryAgainBtn: 'Essayer le Mot Suivant ←',
    wrongToastTitle: 'Réessayez ! ❌',
    wrongToastDesc: (chosen, correct, breakdown) => `Vous avez cliqué sur "${chosen}". La bonne réponse est "${correct}" ${breakdown ? `(${breakdown})` : ''}. Lisez sans étirer !`,
    correctToastTitle: 'Macha\'Allah ! Bonne Réponse 🎉',
    correctToastDesc: 'Très bien ! Vous avez identifié le mot avec exactitude.',
  },
};

export const getMutaharrikatLocalization = (lang: LanguageCode = 'ur'): MutaharrikatGameTexts => {
  return MUTAHARRIKAT_LOCALIZATION[lang] || MUTAHARRIKAT_LOCALIZATION.ur;
};
