import { LanguageCode } from '../types';

export interface PuzzleGameTexts {
  headerTitle: string;
  headerBadge: string;
  headerSubtitle: string;
  backBtn: string;
  soundOn: string;
  soundOff: string;
  previousItem: string;
  nextItem: string;
  listenQari: string;
  listenSpelling: string;
  tapToPlace: string;
  completedTitle: string;
  completedSubtitle: string;
  tryAgain: string;
  slotEmpty: string;

  // 14 Mode Names & Subtitles
  m1Name: string;
  m1Sub: string;
  m2Name: string;
  m2Sub: string;
  m3Name: string;
  m3Sub: string;
  m4Name: string;
  m4Sub: string;
  m5Name: string;
  m5Sub: string;
  m6Name: string;
  m6Sub: string;
  m7Name: string;
  m7Sub: string;
  m8Name: string;
  m8Sub: string;
  m9Name: string;
  m9Sub: string;
  m10Name: string;
  m10Sub: string;
  m11Name: string;
  m11Sub: string;
  m12Name: string;
  m12Sub: string;
  m13Name: string;
  m13Sub: string;
  m14Name: string;
  m14Sub: string;
}

export const PUZZLE_GAME_LOCALIZATION: Record<LanguageCode, PuzzleGameTexts> = {
  ur: {
    headerTitle: 'حروف جوڑ مقناطیسی پزل گیم',
    headerBadge: 'تمام اسباق (۱۴ بڑے موڈز) ✨',
    headerSubtitle: 'مفردات، مرکبات، حرکات، سکون، مدہ، لین، کھڑی حرکات، تنوین، تشدید، نون ساکن، میم ساکن، تفخیم و ترقیق اور سورتیں',
    backBtn: 'واپسی',
    soundOn: 'آواز آن کریں',
    soundOff: 'آواز بند کریں',
    previousItem: 'پچھلا آئٹم',
    nextItem: 'اگلا آئٹم',
    listenQari: 'قاری کی آواز سنیں',
    listenSpelling: 'ہجے سنیں',
    tapToPlace: 'خانے میں حرف رکھنے کے لیے ٹیپ کریں',
    completedTitle: 'ماشاء اللہ! پزل مکمل ہو گیا 🎉',
    completedSubtitle: 'تمام حروف صحیح ترتیب میں رکھے گئے!',
    tryAgain: 'دوبارہ کوشش کریں',
    slotEmpty: 'خالی خانہ',

    m1Name: '۱. مفردات',
    m1Sub: '۲۹ حروفِ تہجی',
    m2Name: '۲. مرکبات',
    m2Sub: '۲ و ۳ حرفی جوڑ',
    m3Name: '۳. متحرکات',
    m3Sub: 'زَبَر ، زَیْر ، پَیْش',
    m4Name: '۴. سکون و قلقلہ',
    m4Sub: 'جزم و قلقلہ',
    m5Name: '۵. حروفِ لین',
    m5Sub: 'واؤ لین و یاء لین',
    m6Name: '۶. حروفِ مَدَّہ',
    m6Sub: 'الف، واؤ، یاء مدہ',
    m7Name: '۷. کھڑی حرکات',
    m7Sub: 'کھڑا زبر، زیر، الٹا پیش',
    m8Name: '۸. تَنْوِیْن',
    m8Sub: 'دو زبر، دو زیر، دو پیش',
    m9Name: '۹. تَشْدِیْد',
    m9Sub: 'مشدد کلمات و غنہ',
    m10Name: '۱۰. نون ساکن',
    m10Sub: 'اظہار، اخفاء، ادغام، اقلاب',
    m11Name: '۱۱. میم ساکن',
    m11Sub: 'ادغام، اخفاء، اظہار شفوی',
    m12Name: '۱۲. تفخیم و ترقیق',
    m12Sub: 'الف، لامِ جلالت و راء',
    m13Name: '۱۳. مَدَّات کے قواعد',
    m13Sub: 'متصل، منفصل، لازم و عارض',
    m14Name: '۱۴. سورتیں',
    m14Sub: 'پارہ عم + الفاتحہ',
  },
  en: {
    headerTitle: 'Magnetic Letter Connector Puzzle Game',
    headerBadge: 'All Lessons (14 Modes) ✨',
    headerSubtitle: 'Individual letters, compounds, vowels, sukoon, maddah, leen, standing vowels, tanween, shaddah, nun/meem sakin & surahs',
    backBtn: 'Back',
    soundOn: 'Unmute Audio',
    soundOff: 'Mute Audio',
    previousItem: 'Previous Item',
    nextItem: 'Next Item',
    listenQari: 'Listen to Qari',
    listenSpelling: 'Listen to Spelling',
    tapToPlace: 'Tap tile to place in slot',
    completedTitle: 'MashaAllah! Puzzle Completed 🎉',
    completedSubtitle: 'All letters connected in the correct order!',
    tryAgain: 'Try Again',
    slotEmpty: 'Empty Slot',

    m1Name: '1. Single Letters',
    m1Sub: '29 Arabic Letters',
    m2Name: '2. Compounds',
    m2Sub: '2 & 3 Letter Joins',
    m3Name: '3. Short Vowels',
    m3Sub: 'Fathah, Kasrah, Dammah',
    m4Name: '4. Sukoon & Qalqalah',
    m4Sub: 'Jazm & Echo Sound',
    m5Name: '5. Soft Letters (Leen)',
    m5Sub: 'Waw Leen & Yaa Leen',
    m6Name: '6. Long Vowels (Maddah)',
    m6Sub: 'Alif, Waw, Yaa Maddah',
    m7Name: '7. Standing Vowels',
    m7Sub: 'Standing Fathah/Kasrah/Dammah',
    m8Name: '8. Tanween',
    m8Sub: 'Double Vowels (-an, -in, -un)',
    m9Name: '9. Shaddah (Tashdeed)',
    m9Sub: 'Doubled Letters & Ghunnah',
    m10Name: '10. Nun Sakin',
    m10Sub: 'Izhar, Ikhfa, Idgham, Iqlab',
    m11Name: '11. Meem Sakin',
    m11Sub: 'Idgham, Ikhfa, Izhar Shafawi',
    m12Name: '12. Thick & Thin Letters',
    m12Sub: 'Alif, Lam Jalalah & Raa',
    m13Name: '13. Types of Madd',
    m13Sub: 'Muttasil, Munfasil, Lazim',
    m14Name: '14. Surahs',
    m14Sub: 'Juz Amma + Al-Fatihah',
  },
  ar: {
    headerTitle: 'لعبة تركيب الحروف والكلمات المغناطيسية',
    headerBadge: 'جميع الدروس (١٤ نمطاً تعليمياً) ✨',
    headerSubtitle: 'المفردات، المركبات، الحركات، السكون، اللين، المد، التنوين، التشديد، النون والميم الساكنتان والسور',
    backBtn: 'رجوع',
    soundOn: 'تشغيل الصوت',
    soundOff: 'كتم الصوت',
    previousItem: 'العنصر السابق',
    nextItem: 'العنصر التالي',
    listenQari: 'استمع إلى القارئ',
    listenSpelling: 'استمع إلى التهجي',
    tapToPlace: 'انقر لوضع الحرف في مكانه',
    completedTitle: 'ما شاء الله! اكتمل اللغز بنجاح 🎉',
    completedSubtitle: 'تم ترتيب جميع الحروف بالترتيب الصحيح!',
    tryAgain: 'حاول مرة أخرى',
    slotEmpty: 'خانة فارغة',

    m1Name: '١. الحروف المفردة',
    m1Sub: '٢٩ حرفاً هجائياً',
    m2Name: '٢. الحروف المركبة',
    m2Sub: 'تركيب حرفين وثلاثة',
    m3Name: '٣. الحركات',
    m3Sub: 'الفتحة، الكسرة، الضمة',
    m4Name: '٤. السكون والقلقلة',
    m4Sub: 'الجزم وحروف القلقلة',
    m5Name: '٥. حروف اللين',
    m5Sub: 'واو اللين وياء اللين',
    m6Name: '٦. حروف المد',
    m6Sub: 'الألف، الواو، الياء المدية',
    m7Name: '٧. الحركات القائمة',
    m7Sub: 'فتحة وكسرة قائمة وضمة مقلوبة',
    m8Name: '٨. التنوين',
    m8Sub: 'تنوين الفتح والكسر والضم',
    m9Name: '٩. التشديد',
    m9Sub: 'الحرف المشدد والغنة',
    m10Name: '١٠. النون الساكنة',
    m10Sub: 'إظهار، إخفاء، إدغام، إقلاب',
    m11Name: '١١. الميم الساكنة',
    m11Sub: 'إدغام، إخفاء، إظهار شفوي',
    m12Name: '١٢. التفخيم والترقيق',
    m12Sub: 'الألف ولام الجلالة والراء',
    m13Name: '١٣. أحكام المدود',
    m13Sub: 'المتصل، المنفصل، اللازم',
    m14Name: '١٤. سور القرآن',
    m14Sub: 'جزء عم + الفاتحة',
  },
  hi: {
    headerTitle: 'अक्षर जोड़ मैग्नेटिक पहेली गेम',
    headerBadge: 'सभी सबक (१४ बड़े मोड्स) ✨',
    headerSubtitle: 'मुफ़्रदात, मुरक्कबात, हरकत, सुकून, मद्ह, लीन, खड़ी हरकत, तनवीन, तशदीद, नून साकिन, मीम साकिन व सूरहें',
    backBtn: 'वापसी',
    soundOn: 'आवाज़ चालू करें',
    soundOff: 'आवाज़ बंद करें',
    previousItem: 'पिछला शब्द',
    nextItem: 'अगला शब्द',
    listenQari: 'क़ारी की आवाज़ सुनें',
    listenSpelling: 'हिज्जे सुनें',
    tapToPlace: 'अक्षर रखने के लिए टैप करें',
    completedTitle: 'माशाअल्लाह! पहेली पूरी हुई 🎉',
    completedSubtitle: 'सभी अक्षर सही क्रम में जोड़े गए!',
    tryAgain: 'दोबारा प्रयास करें',
    slotEmpty: 'खाली जगह',

    m1Name: '१. मुफ़्रदात',
    m1Sub: '२९ अरबी वर्णमाला',
    m2Name: '२. मुरक्कबात',
    m2Sub: '२ व ३ अक्षरों का जोड़',
    m3Name: '३. हरकतें',
    m3Sub: 'ज़बर, ज़ेर, पेश',
    m4Name: '४. सुकून व क़लक़ला',
    m4Sub: 'जज़्म व गूंज',
    m5Name: '५. हुरूफ़-ए-लीन',
    m5Sub: 'वाव लीन व या लीन',
    m6Name: '६. हुरूफ़-ए-मद्दा',
    m6Sub: 'अलिफ़, वाव, या मद्दा',
    m7Name: '७. खड़ी हरकतें',
    m7Sub: 'खड़ा ज़बर, ज़ेर, उल्टा पेश',
    m8Name: '८. तनवीन',
    m8Sub: 'दो ज़बर, दो ज़ेर, दो पेश',
    m9Name: '९. तशदीद',
    m9Sub: 'मुशद्दद शब्द व ग़ुन्ना',
    m10Name: '१०. नून साकिन',
    m10Sub: 'इज़हार, इख़्फ़ा, इदग़ाम, इक़लाब',
    m11Name: '११. मीम साकिन',
    m11Sub: 'इदग़ाम, इख़्फ़ा, इज़हार शफ़वी',
    m12Name: '१२. तफ़ख़ीम व तरक़ीक़',
    m12Sub: 'मोटे व बारीक अक्षर',
    m13Name: '१३. मद्दात के नियम',
    m13Sub: 'मुत्तसिल, मुनफ़सिल, लाज़िम',
    m14Name: '१४. क़ुरआनी सूरहें',
    m14Sub: 'पारा अम्मा + अल-फ़ातिहा',
  },
  bn: {
    headerTitle: 'হরফ জোড়া চৌম্বকীয় ধাঁধা গেম',
    headerBadge: 'সকল পাঠ (১৪টি মোড) ✨',
    headerSubtitle: 'মুফরাদাত, মুরাক্কাবাত, হরকত, সুকূন, মাদ্দাহ, লীন, খাড়া হরকত, তানভীন, তাশদীদ, নূন ও মীম সাকিন ও সূরাসমূহ',
    backBtn: 'ফিরে যান',
    soundOn: 'শব্দ চালু করুন',
    soundOff: 'শব্দ বন্ধ করুন',
    previousItem: 'পূর্ববর্তী শব্দ',
    nextItem: 'পরবর্তী শব্দ',
    listenQari: 'ক্বারীর কণ্ঠ শুনুন',
    listenSpelling: 'বানান শুনুন',
    tapToPlace: 'হরফ বসাতে ট্যাপ করুন',
    completedTitle: 'মাশাআল্লাহ! ধাঁধা সম্পন্ন হয়েছে 🎉',
    completedSubtitle: 'সকল হরফ সঠিক ক্রমানুসারে সাজানো হয়েছে!',
    tryAgain: 'আবার চেষ্টা করুন',
    slotEmpty: 'খালি ঘর',

    m1Name: '১. মুফরাদাত',
    m1Sub: '২৯টি আরবি হরফ',
    m2Name: '২. মুরাক্কাবাত',
    m2Sub: '২ ও ৩ হরফের জোড়া',
    m3Name: '৩. হরকত',
    m3Sub: 'যবর, যের, পেশ',
    m4Name: '৪. সুকূন ও কলকলাহ',
    m4Sub: 'জযম ও প্রতিধ্বনি',
    m5Name: '৫. হরফে লীন',
    m5Sub: 'ওয়াও লীন ও ইয়া লীন',
    m6Name: '৬. হরফে মাদ্দাহ',
    m6Sub: 'আলিফ, ওয়াও, ইয়া মাদ্দাহ',
    m7Name: '৭. খাড়া হরকত',
    m7Sub: 'খাড়া যবর, যের, উল্টা পেশ',
    m8Name: '৮. তানভীন',
    m8Sub: 'দুই যবর, দুই যের, দুই পেশ',
    m9Name: '৯. তাশদীদ',
    m9Sub: 'মুশাদ্দাদ ও গুন্নাহ',
    m10Name: '১০. নূন সাকিন',
    m10Sub: 'ইজহার, ইখফা, ইদগাম, ইকলাব',
    m11Name: '১১. মীম সাকিন',
    m11Sub: 'ইদগাম, ইখফা, ইজহার শাফাবী',
    m12Name: '১২. তাফখীম ও তারকীক',
    m12Sub: 'ভারী ও হালকা হরফ',
    m13Name: '১৩. মাদ্দের নিয়ম',
    m13Sub: 'মুত্তাসিল, মুনফাসিল, লাজিম',
    m14Name: '১৪. সূরাসমূহ',
    m14Sub: 'আমপারা + সূরা আল-ফাতিহা',
  },
  id: {
    headerTitle: 'Game Teka-teki Sambung Huruf Magnetik',
    headerBadge: 'Semua Pelajaran (14 Mode) ✨',
    headerSubtitle: 'Huruf tunggal, sambung, harakat, sukun, mad, lin, tanwin, tasydid, nun/mim mati, tafkhim dan surah',
    backBtn: 'Kembali',
    soundOn: 'Nyalakan Audio',
    soundOff: 'Bisukan Audio',
    previousItem: 'Kata Sebelumnya',
    nextItem: 'Kata Selanjutnya',
    listenQari: 'Dengarkan Qari',
    listenSpelling: 'Dengarkan Ejaan',
    tapToPlace: 'Ketuk huruf untuk menempatkan',
    completedTitle: 'Maa Syaa Allah! Teka-teki Selesai 🎉',
    completedSubtitle: 'Semua huruf tersusun dalam urutan yang tepat!',
    tryAgain: 'Coba Lagi',
    slotEmpty: 'Kotak Kosong',

    m1Name: '1. Huruf Tunggal',
    m1Sub: '29 Huruf Hijaiyah',
    m2Name: '2. Huruf Sambung',
    m2Sub: 'Sambungan 2 & 3 Huruf',
    m3Name: '3. Harakat',
    m3Sub: 'Fathah, Kasrah, Dammah',
    m4Name: '4. Sukun & Qalqalah',
    m4Sub: 'Tanda Mati & Pantulan',
    m5Name: '5. Huruf Lin',
    m5Sub: 'Waw Lin & Ya Lin',
    m6Name: '6. Huruf Mad',
    m6Sub: 'Alif, Waw, Ya Mad',
    m7Name: '7. Harakat Berdiri',
    m7Sub: 'Fathah/Kasrah Berdiri, Dammah Terbalik',
    m8Name: '8. Tanwin',
    m8Sub: 'Fathatain, Kasratain, Dammatain',
    m9Name: '9. Tasydid',
    m9Sub: 'Huruf Bersyaddah & Dengung',
    m10Name: '10. Nun Mati',
    m10Sub: 'Idzhar, Ikhfa, Idgham, Iqlab',
    m11Name: '11. Mim Mati',
    m11Sub: 'Idgham, Ikhfa, Idzhar Syafawi',
    m12Name: '12. Tebal & Tipis',
    m12Sub: 'Alif, Lam Jalalah & Ra',
    m13Name: '13. Macam-macam Mad',
    m13Sub: 'Muttashil, Munfashil, Lazim',
    m14Name: '14. Surah Pendek',
    m14Sub: 'Juz Amma + Al-Fatihah',
  },
  tr: {
    headerTitle: 'Manyetik Harf Birleştirme Yapbozu',
    headerBadge: 'Tüm Dersler (14 Farklı Mod) ✨',
    headerSubtitle: 'Ayrı harfler, bitişik harfler, harekeler, cezim, med, lin, tenvin, şedde, sakin nun/mim, kalın/ince harfler ve sureler',
    backBtn: 'Geri',
    soundOn: 'Sesi Aç',
    soundOff: 'Sesi Kapat',
    previousItem: 'Önceki Kelime',
    nextItem: 'Sonraki Kelime',
    listenQari: 'Kariden Dinle',
    listenSpelling: 'Hecelenmiş Dinle',
    tapToPlace: 'Harfi yerleştirmek için dokunun',
    completedTitle: 'Maşallah! Yapboz Tamamlandı 🎉',
    completedSubtitle: 'Bütün harfler doğru sırada birleştirildi!',
    tryAgain: 'Tekrar Dene',
    slotEmpty: 'Boş Yuva',

    m1Name: '1. Tek Harfler',
    m1Sub: '29 Elifba Harfi',
    m2Name: '2. Bitişik Harfler',
    m2Sub: '2 ve 3 Harfli Birleşimler',
    m3Name: '3. Harekeler',
    m3Sub: 'Üstün, Esre, Ötre',
    m4Name: '4. Cezim ve Kalkale',
    m4Sub: 'Sakin Harf ve Vurgu',
    m5Name: '5. Lin Harfleri',
    m5Sub: 'Vav ve Ya Lin',
    m6Name: '6. Med Harfleri',
    m6Sub: 'Elif, Vav, Ya Meddi',
    m7Name: '7. Çekerli Harekeler',
    m7Sub: 'Dik Üstün, Esre, Ters Ötre',
    m8Name: '8. Tenvin',
    m8Sub: 'İki Üstün, İki Esre, İki Ötre',
    m9Name: '9. Şedde',
    m9Sub: 'Şeddeli Harfler ve Gunne',
    m10Name: '10. Sakin Nun',
    m10Sub: 'İzhar, İhfa, İdgam, İklab',
    m11Name: '11. Sakin Mim',
    m11Sub: 'İdgam, İhfa, Dudak İzharı',
    m12Name: '12. Kalın ve İnce',
    m12Sub: 'Elif, Lafzatullah ve Ra',
    m13Name: '13. Med Çeşitleri',
    m13Sub: 'Muttasıl, Munfasıl, Lazım',
    m14Name: '14. Sureler',
    m14Sub: 'Amme Cüzü + Fatiha',
  },
  fr: {
    headerTitle: 'Jeu de Puzzle Magnétique d\'Assemblage',
    headerBadge: 'Toutes les Leçons (14 Modes) ✨',
    headerSubtitle: 'Lettres isolées, attachées, voyelles, sukoon, maddah, leen, tanween, tashdeed, nun/meem sakin, emphase et sourates',
    backBtn: 'Retour',
    soundOn: 'Activer le son',
    soundOff: 'Couper le son',
    previousItem: 'Élément précédent',
    nextItem: 'Élément suivant',
    listenQari: 'Écouter le Récitateur',
    listenSpelling: 'Écouter l\'Épellation',
    tapToPlace: 'Touchez pour placer la lettre',
    completedTitle: 'Macha\'Allah ! Puzzle Complété 🎉',
    completedSubtitle: 'Toutes les lettres sont correctement assemblées !',
    tryAgain: 'Réessayer',
    slotEmpty: 'Case vide',

    m1Name: '1. Lettres Isolées',
    m1Sub: '29 Lettres Arabes',
    m2Name: '2. Lettres Attachées',
    m2Sub: 'Jointures de 2 & 3 lettres',
    m3Name: '3. Voyelles Brèves',
    m3Sub: 'Fathah, Kasrah, Dammah',
    m4Name: '4. Sukoon & Qalqalah',
    m4Sub: 'Jazm et rebond sonore',
    m5Name: '5. Lettres de Leen',
    m5Sub: 'Waw Leen & Yaa Leen',
    m6Name: '6. Voyelles Longues (Maddah)',
    m6Sub: 'Alif, Waw, Yaa Maddah',
    m7Name: '7. Voyelles Verticales',
    m7Sub: 'Fathah/Kasrah/Dammah longues',
    m8Name: '8. Tanween',
    m8Sub: 'Doubles voyelles (-an, -in, -un)',
    m9Name: '9. Tashdeed (Chadda)',
    m9Sub: 'Lettres doublées & Ghunnah',
    m10Name: '10. Nun Sakin',
    m10Sub: 'Izhar, Ikhfa, Idgham, Iqlab',
    m11Name: '11. Meem Sakin',
    m11Sub: 'Idgham, Ikhfa, Izhar Labial',
    m12Name: '12. Lettres Emphatiques',
    m12Sub: 'Alif, Lam d\'Allah et Raa',
    m13Name: '13. Règles des Maddat',
    m13Sub: 'Muttasil, Munfasil, Lazim',
    m14Name: '14. Sourates',
    m14Sub: 'Juz Amma + Al-Fatiha',
  },
};

export const getPuzzleGameLocalization = (lang: LanguageCode = 'ur'): PuzzleGameTexts => {
  return PUZZLE_GAME_LOCALIZATION[lang] || PUZZLE_GAME_LOCALIZATION.ur;
};
