import { LanguageCode } from '../types';

export interface SukoonGameTexts {
  badgeTitle: string;
  headerTitle: string;
  headerSubtitle: string;
  backBtn: string;
  score: string;
  coins: string;
  streak: string;
  bestStreak: string;
  selectCategory: string;
  soundOnlyMode: string;
  soundOnlyModeActive: string;
  speedChallenge: string;
  timeLeft: string;
  catAll: string;
  catAllDesc: string;
  catTwoLetter: string;
  catTwoLetterDesc: string;
  catThreePlus: string;
  catThreePlusDesc: string;
  catQalqalah: string;
  catQalqalahDesc: string;
  catHamzahSakin: string;
  catHamzahSakinDesc: string;
  catHeavySakin: string;
  catHeavySakinDesc: string;
  listenTargetPrompt: string;
  listenAgain: string;
  listenWord: string;
  listenSpelling: string;
  tajweedRule: string;
  lifeline5050: string;
  insufficientCoins: string;
  insufficientCoinsDesc: string;
  lifelineUsed: string;
  lifelineUsedDesc: string;
  chooseCorrectCard: string;
  questionNum: (current: number, total: number) => string;
  eliminated: string;
  badgeQalqalah: string;
  badgeJolt: string;
  voicePracticeTitle: string;
  voicePracticeDesc: (word: string) => string;
  voiceTest: string;
  voiceRecording: string;
  voicePromptFeedback: string;
  voiceSuccessFeedback: (word: string) => string;
  prevQuestion: string;
  nextQuestion: string;
  ruleModalTitle: (word: string) => string;
  ruleWordRule: string;
  ruleBasicDirectives: string;
  ruleSukoonDesc: string;
  ruleQalqalahDesc: string;
  ruleHamzahDesc: string;
  ruleHeavyDesc: string;
  understoodClose: string;
  correctToastTitle: string;
  wrongToastTitle: string;
  timeUpToastTitle: string;
}

export const SUKOON_GAME_LOCALIZATION: Record<LanguageCode, SukoonGameTexts> = {
  ur: {
    badgeTitle: 'سبق ۴ گیم',
    headerTitle: 'صوتی و بصری گیم: ۲ حرفی و ۳ حرفی ساکن کلمات و قلقلہ 🎯',
    headerSubtitle: 'أَبْ، قُلْ، يَعْلَمُ، يَأْكُلُ، أَطْعَمَ اور خَلَقْنَا جیسے ساکن حروف، قلقلہ اور ہمزہ ساکنہ کی صوتی و بصری مشق',
    backBtn: 'واپسی',
    score: 'اسکور',
    coins: 'کوائنز',
    streak: 'اسٹریک',
    bestStreak: 'بہترین اسٹریک',
    selectCategory: 'کیٹیگری منتخب کریں:',
    soundOnlyMode: '🎧 صرف سن کر بوجھیں',
    soundOnlyModeActive: '🎧 صرف سن کر بوجھیں (فعال)',
    speedChallenge: '⚡ ۶۰ سیکنڈ اسپیڈ چیلنج',
    timeLeft: 'وقت',
    catAll: '🌟 تمام ساکن کلمات',
    catAllDesc: 'جامع مشق',
    catTwoLetter: '🔤 ۲ حرفی ساکن',
    catTwoLetterDesc: 'أَبْ، قُلْ، مَنْ',
    catThreePlus: '📖 ۳ و ۴ حرفی',
    catThreePlusDesc: 'يَعْلَمُ، أَنْعَمْتَ',
    catQalqalah: '💥 قلقلہ (قُطْبُ جَدٍّ)',
    catQalqalahDesc: 'أَقْ، أَطْ، أَجْرٌ',
    catHamzahSakin: '⚡ ہمزہ ساکنہ (جھٹکا)',
    catHamzahSakinDesc: 'يَأْكُلُ، يُؤْمِنُ',
    catHeavySakin: '🟢 حروفِ مستعلیہ',
    catHeavySakinDesc: 'خَ، صَ، ضَ، طَ...',
    listenTargetPrompt: 'قاری صاحب کی تلاوت سن کر درست لفظ چنیں 🎧',
    listenAgain: 'دوبارہ سنیں',
    listenWord: 'روانی تلاوت سنیں (Word)',
    listenSpelling: 'ہجے و جوڑ کا صوتی سلسلہ (Spelling)',
    tajweedRule: 'تجویدی قاعدہ 💡',
    lifeline5050: '50:50 لائف لائن (10 🪙)',
    insufficientCoins: 'سکے ناکافی ہیں! 🪙',
    insufficientCoinsDesc: '50:50 لائف لائن کے لیے کم از کم ۱۰ سکے درکار ہیں۔',
    lifelineUsed: '50:50 لائف لائن فعال! 💡',
    lifelineUsedDesc: 'دو غلط جوابات خارج کر دیے گئے ہیں۔ -10 سکے',
    chooseCorrectCard: 'درست کارڈ کا انتخاب فرمائیں:',
    questionNum: (c, t) => `سوال نمبر ${c} از ${t}`,
    eliminated: 'خارج شدہ',
    badgeQalqalah: 'قلقلہ',
    badgeJolt: 'جھٹکا',
    voicePracticeTitle: 'صوتی مشق: خود تلفظ کر کے آزمائیں',
    voicePracticeDesc: (word) => `مائیک پر کلک کریں اور ساکن لفظ "${word}" کو تجوید کے ساتھ پڑھیں`,
    voiceTest: 'مائیک ٹیسٹ',
    voiceRecording: 'آواز ریکارڈ ہو رہی ہے...',
    voicePromptFeedback: 'براہ کرم مائیک کے قریب سکون اور قلقلہ کے ساتھ صاف تلفظ فرمائیں...',
    voiceSuccessFeedback: (word) => `ماشاء اللہ! آپ کا تلفظ "${word}" بالکل صحیح، جزم کے وقار اور قلقلہ کے ساتھ تھا! ✨`,
    prevQuestion: 'پچھلا سوال',
    nextQuestion: 'اگلا سوال ▶',
    ruleModalTitle: (word) => `تجویدی رہنمائی: ${word}`,
    ruleWordRule: '📌 لفظ کا قاعدہ:',
    ruleBasicDirectives: '✨ بنیادی تجویدی ہدایات:',
    ruleSukoonDesc: 'سکون (جزم): جس حرف پر جزم ہو اسے پچھلے متحرک حرف سے ملا کر پڑھا جاتا ہے۔',
    ruleQalqalahDesc: 'قلقلہ (قُطْبُ جَدٍّ): ق، ط، ب، ج، د جب ساکن ہوں تو ان کے مخرج میں جنبش اور آواز میں گونج پیدا کی جاتی ہے۔',
    ruleHamzahDesc: 'ہمزہ ساکنہ (أْ، ؤْ، ئْ): جب ہمزہ پر جزم ہو تو اسے ہمیشہ سختی سے جھٹکا دے کر پڑھا جاتا ہے۔',
    ruleHeavyDesc: 'حروفِ مستعلیہ: خ، ص، ض، ط، ظ، غ، ق ساکن حالت میں بھی موٹے (پُر) پڑھے جاتے ہیں۔',
    understoodClose: 'سمجھ گیا! واپس گیم کھیلیں 👍',
    correctToastTitle: 'ماشاء اللہ! بالکل درست 🎉',
    wrongToastTitle: 'دوبارہ کوشش کریں! ❌',
    timeUpToastTitle: 'وقت ختم ہو گیا! ⏱️',
  },
  en: {
    badgeTitle: 'Lesson 4 Game',
    headerTitle: 'Audio-Visual Game: 2 & 3 Letter Sakin Words & Qalqalah 🎯',
    headerSubtitle: 'Audio-visual practice for sukoon letters, qalqalah echoes, and hamzah sakinah jolts',
    backBtn: 'Back',
    score: 'Score',
    coins: 'Coins',
    streak: 'Streak',
    bestStreak: 'Best Streak',
    selectCategory: 'Select Category:',
    soundOnlyMode: '🎧 Audio Only Challenge',
    soundOnlyModeActive: '🎧 Audio Only (Active)',
    speedChallenge: '⚡ 60s Speed Challenge',
    timeLeft: 'Time',
    catAll: '🌟 All Sakin Words',
    catAllDesc: 'Full Practice',
    catTwoLetter: '🔤 2-Letter Sakin',
    catTwoLetterDesc: 'أَبْ، قُلْ، مَنْ',
    catThreePlus: '📖 3 & 4 Letters',
    catThreePlusDesc: 'يَعْلَمُ، أَنْعَمْتَ',
    catQalqalah: '💥 Qalqalah (قُطْبُ جَدٍّ)',
    catQalqalahDesc: 'أَقْ، أَطْ، أَجْرٌ',
    catHamzahSakin: '⚡ Hamzah Sakinah (Jolt)',
    catHamzahSakinDesc: 'يَأْكُلُ، يُؤْمِنُ',
    catHeavySakin: '🟢 Heavy Letters',
    catHeavySakinDesc: 'خَ، صَ، ضَ، طَ...',
    listenTargetPrompt: 'Listen to the Qari and select the matching word 🎧',
    listenAgain: 'Listen Again',
    listenWord: 'Listen Word Recitation',
    listenSpelling: 'Spelling Breakdown',
    tajweedRule: 'Tajweed Rule 💡',
    lifeline5050: '50:50 Lifeline (10 🪙)',
    insufficientCoins: 'Insufficient Coins! 🪙',
    insufficientCoinsDesc: '50:50 lifeline requires at least 10 coins.',
    lifelineUsed: '50:50 Lifeline Activated! 💡',
    lifelineUsedDesc: 'Two incorrect choices removed. -10 coins',
    chooseCorrectCard: 'Choose the correct card:',
    questionNum: (c, t) => `Question ${c} of ${t}`,
    eliminated: 'Eliminated',
    badgeQalqalah: 'Qalqalah',
    badgeJolt: 'Jolt',
    voicePracticeTitle: 'Voice Practice: Speak and Verify',
    voicePracticeDesc: (word) => `Click the mic and pronounce the word "${word}" with Tajweed`,
    voiceTest: 'Mic Test',
    voiceRecording: 'Recording voice...',
    voicePromptFeedback: 'Please pronounce clearly near the mic with sukoon and qalqalah...',
    voiceSuccessFeedback: (word) => `MashaAllah! Your pronunciation of "${word}" was accurate and fluent! ✨`,
    prevQuestion: 'Previous',
    nextQuestion: 'Next Question ▶',
    ruleModalTitle: (word) => `Tajweed Guidance: ${word}`,
    ruleWordRule: '📌 Rule for this word:',
    ruleBasicDirectives: '✨ Core Tajweed Rules:',
    ruleSukoonDesc: 'Sukoon (Jazm): A consonant with sukoon is joined directly to the preceding voweled letter.',
    ruleQalqalahDesc: 'Qalqalah (قُطْبُ جَدٍّ): When Qaf, Taa, Baa, Jeem, or Daal carry sukoon, create an echoing bounce in the sound.',
    ruleHamzahDesc: 'Hamzah Sakinah: When Hamzah carries sukoon, it is pronounced with an emphatic, crisp stop/jolt.',
    ruleHeavyDesc: 'Heavy Letters (Musta\'liyah): Letters like Qaf, Taa, Saad must remain full-mouthed even when sakin.',
    understoodClose: 'Understood! Back to Game 👍',
    correctToastTitle: 'MashaAllah! Absolutely Correct 🎉',
    wrongToastTitle: 'Try Again! ❌',
    timeUpToastTitle: "Time's Up! ⏱️",
  },
  ar: {
    badgeTitle: 'لعبة الدرس الرابع',
    headerTitle: 'لعبة سمعية وبصرية: الكلمات الساكنة والقلقلة 🎯',
    headerSubtitle: 'تدريب سمعي وبصري تفاعلي على الحروف الساكنة، حروف القلقلة، والهمزة الساكنة',
    backBtn: 'رجوع',
    score: 'النقاط',
    coins: 'العملات',
    streak: 'التتابع',
    bestStreak: 'أفضل تتابع',
    selectCategory: 'اختر الفئة:',
    soundOnlyMode: '🎧 تحدي السمع فقط',
    soundOnlyModeActive: '🎧 السمع فقط (مفعّل)',
    speedChallenge: '⚡ تحدي السرعة (٦٠ ثانية)',
    timeLeft: 'الوقت',
    catAll: '🌟 جميع الكلمات الساكنة',
    catAllDesc: 'تدريب شامل',
    catTwoLetter: '🔤 ساكن من حرفين',
    catTwoLetterDesc: 'أَبْ، قُلْ، مَنْ',
    catThreePlus: '📖 ٣ و ٤ أحرف',
    catThreePlusDesc: 'يَعْلَمُ، أَنْعَمْتَ',
    catQalqalah: '💥 قلقلة (قُطْبُ جَدٍّ)',
    catQalqalahDesc: 'أَقْ، أَطْ، أَجْرٌ',
    catHamzahSakin: '⚡ همزة ساكنة (نبرة)',
    catHamzahSakinDesc: 'يَأْكُلُ، يُؤْمِنُ',
    catHeavySakin: '🟢 حروف الاستعلاء',
    catHeavySakinDesc: 'خَ، صَ، ضَ، طَ...',
    listenTargetPrompt: 'استمع إلى تلاوة القارئ واختر الكلمة الصحيحة 🎧',
    listenAgain: 'استمع مجدداً',
    listenWord: 'سماع الكلمة كاملة',
    listenSpelling: 'سماع التهجئة والتفكيك',
    tajweedRule: 'قاعدة تجويدية 💡',
    lifeline5050: 'مساعدة 50:50 (١٠ 🪙)',
    insufficientCoins: 'العملات غير كافية! 🪙',
    insufficientCoinsDesc: 'تحتاج إلى ١٠ عملات على الأقل لاستخدام وسيلة المساعدة.',
    lifelineUsed: 'تم تفعيل المساعدة! 💡',
    lifelineUsedDesc: 'تم حذف إجابتين خاطئتين. -١٠ عملات',
    chooseCorrectCard: 'اختر البطاقة الصحيحة:',
    questionNum: (c, t) => `السؤال ${c} من ${t}`,
    eliminated: 'مستبعد',
    badgeQalqalah: 'قلقلة',
    badgeJolt: 'نبرة',
    voicePracticeTitle: 'تدريب صوتي: انطق بنفسك وتحقق',
    voicePracticeDesc: (word) => `اضغط على الميكروفون وانطق الكلمة "${word}" بأحكام التجويد`,
    voiceTest: 'اختبار الميكروفون',
    voiceRecording: 'جاري تسجيل الصوت...',
    voicePromptFeedback: 'يرجى النطق بوضوح بالقرب من الميكروفون مع السكون والقلقلة...',
    voiceSuccessFeedback: (word) => `ما شاء الله! نطقك للكلمة "${word}" سليم ومتقن بالتجويد! ✨`,
    prevQuestion: 'السؤال السابق',
    nextQuestion: 'السؤال التالي ▶',
    ruleModalTitle: (word) => `إرشاد تجويدي: ${word}`,
    ruleWordRule: '📌 حكم هذه الكلمة:',
    ruleBasicDirectives: '✨ قواعد تجويد أساسية:',
    ruleSukoonDesc: 'السكون: الحرف الساكن يُقرأ متصلاً بالحرف المتحرك الذي قبله.',
    ruleQalqalahDesc: 'القلقلة (قطب جد): اضطراب في المخرج عند النطق بالحرف ساكناً ليسمع له نبرة قوية.',
    ruleHamzahDesc: 'الهمزة الساكنة: تنطق بنبرة واضحة وجلية دون تمطيط.',
    ruleHeavyDesc: 'حروف الاستعلاء: تخص ضغط قظ تفخم دائماً حتى في حالة السكون.',
    understoodClose: 'فهمت! العودة للعبة 👍',
    correctToastTitle: 'ما شاء الله! إجابة صحيحة 🎉',
    wrongToastTitle: 'حاول مرة أخرى! ❌',
    timeUpToastTitle: 'انتهى الوقت! ⏱️',
  },
  hi: {
    badgeTitle: 'सबक़ 4 गेम',
    headerTitle: 'ऑडियो-विजुअल गेम: 2 व 3 हर्फी साकिन शब्द व क़लक़ला 🎯',
    headerSubtitle: 'साकिन हर्फ़, क़लक़ला की गूँज और हमज़ा साकिना का ऑडियो-विज़ुअल अभ्यास',
    backBtn: 'वापस जाएं',
    score: 'स्कोर',
    coins: 'सिक्के',
    streak: 'स्ट्रीक',
    bestStreak: 'सर्वश्रेष्ठ',
    selectCategory: 'श्रेणी चुनें:',
    soundOnlyMode: '🎧 केवल सुनकर पहचानें',
    soundOnlyModeActive: '🎧 केवल सुनकर (सक्रिय)',
    speedChallenge: '⚡ 60 सेकंड स्पीड चैलेंज',
    timeLeft: 'समय',
    catAll: '🌟 सभी साकिन शब्द',
    catAllDesc: 'व्यापक अभ्यास',
    catTwoLetter: '🔤 2-हर्फी साकिन',
    catTwoLetterDesc: 'أَبْ، قُلْ، مَنْ',
    catThreePlus: '📖 3 व 4 हर्फी',
    catThreePlusDesc: 'يَعْلَمُ، أَنْعَمْتَ',
    catQalqalah: '💥 क़लक़ला (قُطْبُ جَدٍّ)',
    catQalqalahDesc: 'أَقْ، أَطْ، أَجْرٌ',
    catHamzahSakin: '⚡ हमज़ा साकिना (झटका)',
    catHamzahSakinDesc: 'يَأْكُلُ، يُؤْمِنُ',
    catHeavySakin: '🟢 मोटे हर्फ़ (मुस्तलिया)',
    catHeavySakinDesc: 'خَ، صَ، ضَ، طَ...',
    listenTargetPrompt: 'क़ारी साहब की तिलावत सुनें और सही शब्द चुनें 🎧',
    listenAgain: 'फिर से सुनें',
    listenWord: 'पूरा शब्द सुनें',
    listenSpelling: 'हिज्जे और जोड़ सुनें',
    tajweedRule: 'तजवीद नियम 💡',
    lifeline5050: '50:50 लाइफलाइन (10 🪙)',
    insufficientCoins: 'सिक्के कम हैं! 🪙',
    insufficientCoinsDesc: '50:50 लाइफलाइन के लिए कम से कम 10 सिक्के चाहिए।',
    lifelineUsed: '50:50 लाइफलाइन सक्रिय! 💡',
    lifelineUsedDesc: 'दो गलत विकल्प हटा दिए गए हैं। -10 सिक्के',
    chooseCorrectCard: 'सही कार्ड चुनें:',
    questionNum: (c, t) => `प्रश्न ${c} / ${t}`,
    eliminated: 'हटाया गया',
    badgeQalqalah: 'क़लक़ला',
    badgeJolt: 'झटका',
    voicePracticeTitle: 'आवाज़ से अभ्यास: स्वयं बोलकर जांचें',
    voicePracticeDesc: (word) => `माइक पर क्लिक करें और साकिन शब्द "${word}" को तजवीद से पढ़ें`,
    voiceTest: 'माइक टेस्ट',
    voiceRecording: 'आवाज़ रिकॉर्ड हो रही है...',
    voicePromptFeedback: 'कृपया माइक के पास सुकूँ और क़लक़ला के साथ साफ़ उच्चारण करें...',
    voiceSuccessFeedback: (word) => `माशाअल्लाह! आपका उच्चारण "${word}" तजवीद के अनुसार बिल्कुल सही था! ✨`,
    prevQuestion: 'पिछला सवाल',
    nextQuestion: 'अगला सवाल ▶',
    ruleModalTitle: (word) => `तजवीद मार्गदर्शन: ${word}`,
    ruleWordRule: '📌 इस शब्द का नियम:',
    ruleBasicDirectives: '✨ बुनियादी तजवीदी हिदायतें:',
    ruleSukoonDesc: 'सुकून (जज़्म): जिस हर्फ़ पर जज़्म हो उसे पिछले हरकत वाले हर्फ़ से मिलाकर पढ़ते हैं।',
    ruleQalqalahDesc: 'क़लक़ला (क़ुत्ब जद): क़ाफ़, ता, बा, जीम, दाल जब साकिन हों तो आवाज़ में उछाल पैदा करते हैं।',
    ruleHamzahDesc: 'हमज़ा साकिना: हमज़ा पर जज़्म हो तो हमेशा झटका देकर पढ़ते हैं।',
    ruleHeavyDesc: 'हुरूफ़े मुस्तलिया: ख़ा, साद, ज़ाद, ता, ज़ा, ग़ैन, क़ाफ़ साकिन हालत में भी भारी/मोटे पढ़े जाते हैं।',
    understoodClose: 'समझ गया! वापस खेलें 👍',
    correctToastTitle: 'माशाअल्लाह! बिल्कुल सही 🎉',
    wrongToastTitle: 'फिर से कोशिश करें! ❌',
    timeUpToastTitle: 'समय समाप्त! ⏱️',
  },
  bn: {
    badgeTitle: 'পাঠ ৪ গেম',
    headerTitle: 'শ্রবণ ও দৃশ্যমান গেম: ২ ও ৩ অক্ষরের সাকিন শব্দ ও ক্বলক্বলাহ 🎯',
    headerSubtitle: 'সাকিন হরফ, ক্বলক্বলার প্রতিধ্বনি এবং হামযাহ সাকিনাহর অডিও-ভিজ্যুয়াল অনুশীলন',
    backBtn: 'ফিরে যান',
    score: 'স্কোর',
    coins: 'কয়েন',
    streak: 'ধারাবাহিকতা',
    bestStreak: 'সেরা ধারা',
    selectCategory: 'ক্যাটাগরি নির্বাচন করুন:',
    soundOnlyMode: '🎧 শুধুমাত্র শুনে চিনুন',
    soundOnlyModeActive: '🎧 শুধুমাত্র শুনে (সক্রিয়)',
    speedChallenge: '⚡ ৬০ সেকেন্ড স্পিড চ্যালেঞ্জ',
    timeLeft: 'সময়',
    catAll: '🌟 সকল সাকিন শব্দ',
    catAllDesc: 'পূর্ণ অনুশীলন',
    catTwoLetter: '🔤 ২-অক্ষরের সাকিন',
    catTwoLetterDesc: 'أَبْ، قُلْ، مَنْ',
    catThreePlus: '📖 ৩ ও ৪ অক্ষরের',
    catThreePlusDesc: 'يَعْلَمُ، أَنْعَمْتَ',
    catQalqalah: '💥 ক্বলক্বলাহ (قُطْبُ جَدٍّ)',
    catQalqalahDesc: 'أَقْ، أَطْ، أَجْرٌ',
    catHamzahSakin: '⚡ হামযাহ সাকিনাহ (ঝাঁকুনি)',
    catHamzahSakinDesc: 'يَأْكُلُ، يُؤْمِنُ',
    catHeavySakin: '🟢 মোটা হরফ (মুস্তা\'লিয়াহ)',
    catHeavySakinDesc: 'خَ، صَ، ضَ، طَ...',
    listenTargetPrompt: 'ক্বারীর তেলওয়াত শুনুন এবং সঠিক শব্দটি নির্বাচন করুন 🎧',
    listenAgain: 'পুনরায় শুনুন',
    listenWord: 'পুরো শব্দ শুনুন',
    listenSpelling: 'বানান ও জোড়া শুনুন',
    tajweedRule: 'তাজবীদ নিয়ম 💡',
    lifeline5050: '৫০:৫০ লাইফলাইন (১০ 🪙)',
    insufficientCoins: 'কয়েন অপর্যাপ্ত! 🪙',
    insufficientCoinsDesc: '৫০:৫০ লাইফলাইনের জন্য কমপক্ষে ১০ কয়েন প্রয়োজন।',
    lifelineUsed: '৫০:৫০ লাইফলাইন সক্রিয়! 💡',
    lifelineUsedDesc: 'দুটি ভুল বিকল্প সরিয়ে দেওয়া হয়েছে। -১০ কয়েন',
    chooseCorrectCard: 'সঠিক কার্ডটি বেছে নিন:',
    questionNum: (c, t) => `প্রশ্ন ${c} / ${t}`,
    eliminated: 'বাদ দেওয়া',
    badgeQalqalah: 'ক্বলক্বলাহ',
    badgeJolt: 'ঝাঁকুনি',
    voicePracticeTitle: 'কণ্ঠ অনুশীলন: উচ্চারণ করে পরীক্ষা করুন',
    voicePracticeDesc: (word) => `মাইকে ক্লিক করুন এবং সাকিন শব্দ "${word}" তাজবীদের সাথে পাঠ করুন`,
    voiceTest: 'মাইক পরীক্ষা',
    voiceRecording: 'কণ্ঠ রেকর্ড হচ্ছে...',
    voicePromptFeedback: 'দয়া করে সুকুন ও ক্বলক্বলার সাথে স্পষ্টভাবে উচ্চারণ করুন...',
    voiceSuccessFeedback: (word) => `মাশাআল্লাহ! "${word}" শব্দটির উচ্চারণ তাজবীদসম্মত ও নির্ভুল হয়েছে! ✨`,
    prevQuestion: 'পূর্ববর্তী',
    nextQuestion: 'পরবর্তী প্রশ্ন ▶',
    ruleModalTitle: (word) => `তাজবীদ নির্দেশিকা: ${word}`,
    ruleWordRule: '📌 এই শব্দের নিয়ম:',
    ruleBasicDirectives: '✨ মৌলিক তাজবীদ নির্দেশনা:',
    ruleSukoonDesc: 'সুকুন (জযম): জযমযুক্ত হরফ পূর্বের হরকতের হরফের সাথে মিলিয়ে পড়তে হয়।',
    ruleQalqalahDesc: 'ক্বলক্বলাহ (ক্বাফ, ত্বোয়া, বা, জীম, দাল): এই হরফগুলোতে জযম হলে প্রতিধ্বনি তৈরি করতে হয়।',
    ruleHamzahDesc: 'হামযাহ সাকিনাহ: হামযাহতে জযম হলে ঝাঁকুনি দিয়ে পড়তে হয়।',
    ruleHeavyDesc: 'মুস্তা\'লিয়াহ হরফ: মোটা হরফগুলো সাকিন হলেও ভারী করে পড়তে হয়।',
    understoodClose: 'বুঝেছি! খেলায় ফিরুন 👍',
    correctToastTitle: 'মাশাআল্লাহ! একদম সঠিক 🎉',
    wrongToastTitle: 'আবার চেষ্টা করুন! ❌',
    timeUpToastTitle: 'সময় শেষ! ⏱️',
  },
  id: {
    badgeTitle: 'Game Pelajaran 4',
    headerTitle: 'Game Audio-Visual: Kata Sakin 2 & 3 Huruf & Qalqalah 🎯',
    headerSubtitle: 'Latihan interaktif sukun, pantulan qalqalah, dan hentakan hamzah sakinah',
    backBtn: 'Kembali',
    score: 'Skor',
    coins: 'Koin',
    streak: 'Streak',
    bestStreak: 'Streak Terbaik',
    selectCategory: 'Pilih Kategori:',
    soundOnlyMode: '🎧 Tantangan Audio Saja',
    soundOnlyModeActive: '🎧 Audio Saja (Aktif)',
    speedChallenge: '⚡ Tantangan Cepat 60 Detik',
    timeLeft: 'Waktu',
    catAll: '🌟 Semua Kata Sakin',
    catAllDesc: 'Latihan Lengkap',
    catTwoLetter: '🔤 Sakin 2 Huruf',
    catTwoLetterDesc: 'أَبْ، قُلْ، مَنْ',
    catThreePlus: '📖 3 & 4 Huruf',
    catThreePlusDesc: 'يَعْلَمُ، أَنْعَمْتَ',
    catQalqalah: '💥 Qalqalah (قُطْبُ جَدٍّ)',
    catQalqalahDesc: 'أَقْ، أَطْ، أَجْرٌ',
    catHamzahSakin: '⚡ Hamzah Sakinah (Hentakan)',
    catHamzahSakinDesc: 'يَأْكُلُ، يُؤْمِنُ',
    catHeavySakin: '🟢 Huruf Tebal (Isti\'la)',
    catHeavySakinDesc: 'خَ، صَ، ضَ، طَ...',
    listenTargetPrompt: 'Dengarkan Qari dan pilih kata yang benar 🎧',
    listenAgain: 'Dengar Lagi',
    listenWord: 'Dengarkan Kata Utuh',
    listenSpelling: 'Ejaan & Penguraian',
    tajweedRule: 'Kaidah Tajwid 💡',
    lifeline5050: 'Bantuan 50:50 (10 🪙)',
    insufficientCoins: 'Koin Tidak Cukup! 🪙',
    insufficientCoinsDesc: 'Bantuan 50:50 memerlukan setidaknya 10 koin.',
    lifelineUsed: 'Bantuan 50:50 Aktif! 💡',
    lifelineUsedDesc: 'Dua pilihan salah disingkirkan. -10 koin',
    chooseCorrectCard: 'Pilih kartu yang benar:',
    questionNum: (c, t) => `Pertanyaan ${c} dari ${t}`,
    eliminated: 'Dieliminasi',
    badgeQalqalah: 'Qalqalah',
    badgeJolt: 'Hentakan',
    voicePracticeTitle: 'Latihan Suara: Ucapkan dan Verifikasi',
    voicePracticeDesc: (word) => `Klik mikrofon dan lafalkan kata "${word}" dengan tajwid`,
    voiceTest: 'Tes Suara',
    voiceRecording: 'Merekam suara...',
    voicePromptFeedback: 'Silakan lafalkan dekat mikrofon dengan sukun dan qalqalah yang jelas...',
    voiceSuccessFeedback: (word) => `MashaAllah! Pelafalan kata "${word}" sangat tepat dan bertajwid! ✨`,
    prevQuestion: 'Sebelumnya',
    nextQuestion: 'Berikutnya ▶',
    ruleModalTitle: (word) => `Panduan Tajwid: ${word}`,
    ruleWordRule: '📌 Kaidah Kata Ini:',
    ruleBasicDirectives: '✨ Kaidah Tajwid Inti:',
    ruleSukoonDesc: 'Sukun (Jazam): Huruf bertanda sukun dibaca bersambung dengan huruf berharakat sebelumnya.',
    ruleQalqalahDesc: 'Qalqalah (Qaf, Tha, Ba, Jim, Dal): Ketika sukun, timbul pantulan suara yang kuat.',
    ruleHamzahDesc: 'Hamzah Sakinah: Hamzah sukun dibaca dengan hentakan yang tegas dan jelas.',
    ruleHeavyDesc: 'Huruf Isti\'la: Huruf tebal tetap dibaca tebal meski dalam keadaan sukun.',
    understoodClose: 'Paham! Kembali Main 👍',
    correctToastTitle: 'MashaAllah! Benar Sekali 🎉',
    wrongToastTitle: 'Coba Lagi! ❌',
    timeUpToastTitle: 'Waktu Habis! ⏱️',
  },
  tr: {
    badgeTitle: 'Ders 4 Oyunu',
    headerTitle: 'Görsel ve İşitsel Oyun: 2 ve 3 Harfli Sakin Kelimeler & Kalkale 🎯',
    headerSubtitle: 'Sükunlu harfler, kalkale yankısı ve hemze-i sakine için işitsel pratik',
    backBtn: 'Geri',
    score: 'Puan',
    coins: 'Jeton',
    streak: 'Seri',
    bestStreak: 'En İyi Seri',
    selectCategory: 'Kategori Seçin:',
    soundOnlyMode: '🎧 Sadece Dinle',
    soundOnlyModeActive: '🎧 Sadece Dinle (Aktif)',
    speedChallenge: '⚡ 60 Saniye Hız Mücadelesi',
    timeLeft: 'Süre',
    catAll: '🌟 Tüm Sakin Kelimeler',
    catAllDesc: 'Kapsamlı Pratik',
    catTwoLetter: '🔤 2 Harfli Sakin',
    catTwoLetterDesc: 'أَبْ، قُلْ، مَنْ',
    catThreePlus: '📖 3 ve 4 Harfli',
    catThreePlusDesc: 'يَعْلَمُ، أَنْعَمْتَ',
    catQalqalah: '💥 Kalkale (قُطْبُ جَدٍّ)',
    catQalqalahDesc: 'أَقْ، أَطْ، أَجْرٌ',
    catHamzahSakin: '⚡ Hemze-i Sakine (Vurgulu)',
    catHamzahSakinDesc: 'يَأْكُلُ، يُؤْمِنُ',
    catHeavySakin: '🟢 Kalın Harfler (İsti\'la)',
    catHeavySakinDesc: 'خَ، صَ، ضَ، طَ...',
    listenTargetPrompt: 'Karinin okuyuşunu dinleyin ve doğru kelimeyi seçin 🎧',
    listenAgain: 'Tekrar Dinle',
    listenWord: 'Kelimeyi Dinle',
    listenSpelling: 'Heceleme ve Çözümleme',
    tajweedRule: 'Tecvid Kuralı 💡',
    lifeline5050: '50:50 Joker (10 🪙)',
    insufficientCoins: 'Jeton Yetersiz! 🪙',
    insufficientCoinsDesc: '50:50 jokeri için en az 10 jeton gereklidir.',
    lifelineUsed: '50:50 Jokeri Aktif! 💡',
    lifelineUsedDesc: 'İki yanlış seçenek elendi. -10 jeton',
    chooseCorrectCard: 'Doğru kartı seçin:',
    questionNum: (c, t) => `Soru ${c} / ${t}`,
    eliminated: 'Elendi',
    badgeQalqalah: 'Kalkale',
    badgeJolt: 'Vurgu',
    voicePracticeTitle: 'Sesli Pratik: Kendiniz Telaffuz Edin',
    voicePracticeDesc: (word) => `Mikrofona tıklayın ve "${word}" kelimesini tecvidle okuyun`,
    voiceTest: 'Mikrofon Testi',
    voiceRecording: 'Ses kaydediliyor...',
    voicePromptFeedback: 'Lütfen mikrofona yakın şekilde sükun ve kalkale ile net telaffuz edin...',
    voiceSuccessFeedback: (word) => `Maşallah! "${word}" kelimesi telaffuzunuz tecvide uygun ve doğru! ✨`,
    prevQuestion: 'Önceki',
    nextQuestion: 'Sonraki Soru ▶',
    ruleModalTitle: (word) => `Tecvid Rehberi: ${word}`,
    ruleWordRule: '📌 Kelimenin Kuralı:',
    ruleBasicDirectives: '✨ Temel Tecvid Kuralları:',
    ruleSukoonDesc: 'Sükun (Cezim): Cezimli harf, kendisinden önceki harekeli harfe bağlanarak okunur.',
    ruleQalqalahDesc: 'Kalkale (Kaf, Tı, Be, Cim, Dal): Sakin olduklarında mahreçte ses yankılanır.',
    ruleHamzahDesc: 'Hemze-i Sakine: Cezimli hemze ses kesilerek belirgin bir vurguyla okunur.',
    ruleHeavyDesc: 'İsti\'la Harfleri: Kalın harfler sakin olsalar dahi kalın okunur.',
    understoodClose: 'Anladım! Oyuna Dön 👍',
    correctToastTitle: 'Maşallah! Kesinlikle Doğru 🎉',
    wrongToastTitle: 'Tekrar Deneyin! ❌',
    timeUpToastTitle: 'Süre Doldu! ⏱️',
  },
  fr: {
    badgeTitle: 'Jeu Leçon 4',
    headerTitle: 'Jeu Audio-Visuel : Mots Sakin de 2 et 3 Lettres & Qalqalah 🎯',
    headerSubtitle: 'Pratique audio-visuelle des lettres avec soukoun, de l\'écho de la qalqalah et de la hamzah sakinah',
    backBtn: 'Retour',
    score: 'Score',
    coins: 'Pièces',
    streak: 'Série',
    bestStreak: 'Meilleure Série',
    selectCategory: 'Choisir la Catégorie :',
    soundOnlyMode: '🎧 Mode Audio Seul',
    soundOnlyModeActive: '🎧 Audio Seul (Actif)',
    speedChallenge: '⚡ Défi Vitesse 60s',
    timeLeft: 'Temps',
    catAll: '🌟 Tous les Mots Sakin',
    catAllDesc: 'Pratique Complète',
    catTwoLetter: '🔤 Sakin 2 Lettres',
    catTwoLetterDesc: 'أَبْ، قُلْ، مَنْ',
    catThreePlus: '📖 3 & 4 Lettres',
    catThreePlusDesc: 'يَعْلَمُ، أَنْعَمْتَ',
    catQalqalah: '💥 Qalqalah (قُطْبُ جَدٍّ)',
    catQalqalahDesc: 'أَقْ، أَطْ، أَجْرٌ',
    catHamzahSakin: '⚡ Hamzah Sakinah (Secousse)',
    catHamzahSakinDesc: 'يَأْكُلُ، يُؤْمِنُ',
    catHeavySakin: '🟢 Lettres Emphatiques',
    catHeavySakinDesc: 'خَ، صَ، ضَ، طَ...',
    listenTargetPrompt: 'Écoutez le Qari et choisissez le bon mot 🎧',
    listenAgain: 'Réécouter',
    listenWord: 'Écouter le Mot Entier',
    listenSpelling: 'Épellation & Décomposition',
    tajweedRule: 'Règle de Tajweed 💡',
    lifeline5050: 'Indice 50:50 (10 🪙)',
    insufficientCoins: 'Pièces Insuffisantes ! 🪙',
    insufficientCoinsDesc: 'L\'indice 50:50 requiert au moins 10 pièces.',
    lifelineUsed: 'Indice 50:50 Activé ! 💡',
    lifelineUsedDesc: 'Deux mauvaises réponses ont été retirées. -10 pièces',
    chooseCorrectCard: 'Choisissez la bonne carte :',
    questionNum: (c, t) => `Question ${c} sur ${t}`,
    eliminated: 'Éliminé',
    badgeQalqalah: 'Qalqalah',
    badgeJolt: 'Secousse',
    voicePracticeTitle: 'Pratique Vocale : Prononcez et Vérifiez',
    voicePracticeDesc: (word) => `Cliquez sur le micro et récitez le mot "${word}" avec Tajweed`,
    voiceTest: 'Test Micro',
    voiceRecording: 'Enregistrement de la voix...',
    voicePromptFeedback: 'Veuillez prononcer distinctement près du micro avec soukoun et qalqalah...',
    voiceSuccessFeedback: (word) => `MachaAllah ! Votre prononciation de "${word}" est très précise avec Tajweed ! ✨`,
    prevQuestion: 'Précédent',
    nextQuestion: 'Question Suivante ▶',
    ruleModalTitle: (word) => `Guide de Tajweed : ${word}`,
    ruleWordRule: '📌 Règle de ce mot :',
    ruleBasicDirectives: '✨ Règles de Tajweed Fondamentales :',
    ruleSukoonDesc: 'Soukoun (Jazm) : Une lettre portant un soukoun est reliée à la lettre précédente avec voyelle.',
    ruleQalqalahDesc: 'Qalqalah (Qaf, Taa, Baa, Jeem, Daal) : Produit un écho ou rebond quand ces lettres sont sakinah.',
    ruleHamzahDesc: 'Hamzah Sakinah : Doit être prononcée avec un arrêt net et marqué (secousse).',
    ruleHeavyDesc: 'Lettres Emphatiques (Musta\'liyah) : Restent pleines et graves même lorsqu\'elles ont un soukoun.',
    understoodClose: 'Compris ! Retour au Jeu 👍',
    correctToastTitle: 'MachaAllah ! Tout à Fait Correct 🎉',
    wrongToastTitle: 'Réessayez ! ❌',
    timeUpToastTitle: 'Temps Écoulé ! ⏱️',
  },
};

export const getSukoonLocalization = (lang: LanguageCode): SukoonGameTexts => {
  return SUKOON_GAME_LOCALIZATION[lang] || SUKOON_GAME_LOCALIZATION.en;
};
